1단계 - 경로 조회 타입 추가
next-step/atdd-subway-fare pull request #115
Opened 2022-02-18 09:24 UTC by monkeyDugi

## 1. *`PathType` enum이 괜찮은 선택일까요?*

타입에 대해 결정되는 것들은 모두 enum으로 위임 했는데 PathFinder가 해야할 일을 대신하고 있는 것 같기도 한데
어떻게 생각 하시나요?

## 2. Sections의 `ddd`() 메서드명을 어떻게 지어야 좋을까요?

## 3. Sections의 `ddd`() 로직을 어떻게 개선하면 좋을까요? 제가 봐도 알아보기 너무 힘드네요 ㅜ.ㅜ

## 4. RestDocs 불편함.

프로덕션용 테스트 코드, 문서용 테스트 코드를 별도로 관리해야 해서 불편하다고 느꼈습니다.
스웨거 같은 경우 프로덕션 코드에 애노테이션이 필요하긴 하지만 훨씬 관리가 편하다고 생각합니다.
RestDocs의 장점이 테스트가 통과해야 문서가 생성되기 때문에 테스트를 강제할 수 있다고 생각하는데
이게 오히려 발목을 잡는 것 같습니다 ㅜ.ㅜ 리뷰어님은 어떻게 생각 하시나요?

## 5. index.adoc에서 **include::path.adoc[]를 찾지 못하는데 어떤 방법으로 고민해봐야 할까요?**

2022-02-18 14:43 UTC, pch8388 requested changes
안녕하세요 병덕님 🙇 
문서를 작성하고 차근차근 구현해나가신 부분이 인상깊었습니다 👍 
참고하실만한 코멘트를 남겨드렸으니 수정하신 후 다시 리뷰요청 해주세요 🔥 🔥

2022-02-18 14:43 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/PathServiceTest.java
> +    void findPath() {
이름으로도 잘 드러나긴 하지만 여기도 `@DisplayName` 을 추가하면 좋을 것 같아요 😄

2022-02-18 14:43 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/PathServiceTest.java
> +        PathResponse path = pathService.findPath(1L, 3L, PathType.DISTANCE);
1L, 3L 도 상수로 정의하면 더 의미가 드러날 것 같아요 😅

2022-02-18 14:43 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/PathFinderTest.java
> +                .hasMessage("노선에 등록되지 않은 역입니다.");
예외 테스트 잘해주셨네요 👍

2022-02-18 14:43 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        Section section2 = new Section(line, 가양역, 증미역, fourDistance, threeDuration);
개인적으로는 테스트내의 변수도 의미있는 이름인 것을 선호합니다 😅

2022-02-18 14:43 UTC, pch8388 commented on src/docs/asciidoc/index.adoc
> +//include::path.adoc[]
```operation::path[snippets='http-request,request-parameters,http-response,response-fields']```

이런 형태로 할 수 있습니다 😄

2022-02-18 14:50 UTC, pch8388 commented
질문하신 부분에 대한 제 생각은 여기서 드리겠습니다.

PathType enum이 괜찮은 선택일까요?

> 해당 클래스에도 리뷰를 드린 부분과 함께 조금 더 제 생각을 말씀드리면, 개발자가 제어할 수 없는 외부 라이브러리의 영향이 이곳 저곳에 퍼지도록 구현하신 것 같아서 이 부분을 일단 수정해야 할 것 같습니다.
말씀하신대로 PathFinder 를 통해 구현하는 것이 조금 더 좋을 것 같습니다. 물론 리뷰를 참고하셔서 수정하시다보면 더 좋은 방법이 나올 수도 있을 것 같아요 😄 

Sections의 ddd() 로직을 어떻게 개선하면 좋을까요? 제가 봐도 알아보기 너무 힘드네요 ㅜ.ㅜ

> 리뷰도 달아드렸지만 일단 너무 많은 일을 하는 건 아닌지부터 고민해보고, 일단 함수로 잘게 나누어보고, 클래스로 나누어야 될지 고민하는 게 좋을 것 같습니다 

RestDocs 불편함.
프로덕션용 테스트 코드, 문서용 테스트 코드를 별도로 관리해야 해서 불편하다고 느꼈습니다.
스웨거 같은 경우 프로덕션 코드에 애노테이션이 필요하긴 하지만 훨씬 관리가 편하다고 생각합니다.
RestDocs의 장점이 테스트가 통과해야 문서가 생성되기 때문에 테스트를 강제할 수 있다고 생각하는데
이게 오히려 발목을 잡는 것 같습니다 ㅜ.ㅜ 리뷰어님은 어떻게 생각 하시나요?

> 테스트를 강제할 수 있는 것 자체가 장점이라고 생각합니다. 테스트 없이 프로덕션 코드가 나가는 것을 방지하는 약간의 제약이라고 생각하시면 좋을 것 같아요. 하지만, 제가 일하는 팀도 현재는 스웨거가 더 많이 적용되어 있긴 합니다 😅

2022-02-18 18:11 UTC, monkeyDugi commented on src/main/java/nextstep/subway/domain/Section.java
> +    private int duration;
Duration도 고민을 했지만, 로직이 존재하지 않아서 과도하도 생각하여 Wrapping하지 않았습니다!

2022-02-18 18:48 UTC, monkeyDugi commented on src/docs/asciidoc/index.adoc
> +//include::path.adoc[]
아예 파일을 통으로는 못하는건가요? 그렇게 하고 싶어서요 ㅜ.ㅜ

2022-02-19 13:15 UTC, monkeyDugi commented
외부 라이브러리가 내부 객체에 의존하면 안되는 이유가 개발자가 제어할 수 없는 부분이기 때문에 그런건가요?
예시로 `라이브러리 메서드가 바꼈을 경우 의존되는 클래스 모두 변경 되어야 한다.`  이런 느낌인가요?

[Section의 updateRemoveLineBetweenSection()이 isBeteweenSection()](https://github.com/next-step/atdd-subway-fare/pull/115#discussion_r809949112)이 피드백은 이해가 잘 안돼서 조금 더 설명이 가능할까요?

2022-02-20 07:06 UTC, pch8388 approved these changes
리팩터링 열심히 해주셨네요 👍 
참고하실만한 내용을 코멘트로 남겨드렸으니 확인 후 다음 스탭 진행해주세요 😄 
이번 스탭은 여기서 Merge 하겠습니다.

2022-02-20 07:06 UTC, pch8388 commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +        경로_조회(given("path", this.getParameterDescriptors(), this.getFieldDescriptors()), source, target, "DURATION");
`RestDocs` 에 대해 여기서 코멘트 드리겠습니다.

개인적으로는 API 스펙을 문서로 만드는 것이기 때문에 Controller [슬라이스 테스트](https://tecoble.techcourse.co.kr/post/2021-05-18-slice-test/)여도 괜찮다고 생각을 합니다.
또는, 엔드포인트에 대해 통합테스트를 하는 형태로 만드셔도 됩니다. 실제 요청하도록 하면 됩니다 😄

2022-02-20 07:08 UTC, merged