🚀 2단계 - 요금 조회
next-step/atdd-subway-fare pull request #129
Opened 2022-02-21 14:42 UTC by soosue

안녕하세요. 2단계 미션 구현해봤습니다!
리뷰 잘 부탁드립니다~😄

2022-02-22 14:21 UTC, kang-hyungu requested changes
윤수님 몇 가지 피드백 남겼습니다.
수정해보시고 피드백 남겨주세요.

2022-02-22 14:21 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/From10To50Policy.java
> +public class From10To50Policy implements SubwayFarePolicy {
요구사항이 바껴서 거리 조건이 10, 60으로 바뀌거나 하면 클래스명도 같이 변경해야겠네요.
이 클래스가 사용되는 코드도 같이 변경이 될테구요.
적절한 다른 용어를 사용해보는게 어떨까요?

2022-02-22 14:21 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/DefaultFarePolicy.java
> +    public DefaultFarePolicy(int fare) {
테스트 때문에 추가한 생성자일까요?
이 생성자가 없어도 되지 않을까요?

2022-02-22 14:21 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/From10To50Policy.java
> +    public int apply(int currentFare, int distance) {
```suggestion
    public int apply(int currentFare, int distance) {
        if (distance <= MIN_DISTANCE) {
            return currentFare;
        }

        if (distance <= MAX_DISTANCE) {
            return currentFare + calculateOverFare(distance - MIN_DISTANCE);
        }

        return currentFare + calculateOverFare(MAX_DISTANCE - MIN_DISTANCE);
    }
```

예외가 발생 할 수 없겠네요.
이렇게 쓰면 더 간결하지 않을까요?

2022-02-22 14:21 UTC, kang-hyungu commented on src/test/java/nextstep/subway/unit/SubwayFareTest.java
> +    private static Stream<Arguments> provideDistanceAndFare() {
테스트를 보니 거의 비슷한 형태로 테스트를 하고 있군요.
비슷한 형태의 테스트를 보니 DefaulltFarePolilcy, From10To50Policy, Over50Policy 이렇게 세 가지 거리정책을 나눌 필요가 있는지 의문이 듭니다.
오히려 구조가 더 복잡하지 않나요?
SubwayFare 클래스에서 거리 조건에 따른 계산만 해줘도 충분하지 않을까요?

2022-02-23 02:56 UTC, soosue commented
피드백 적용해봤는데 한 번 확인해주시면 감사하겠습니다!

2022-02-23 02:58 UTC, soosue commented on src/main/java/nextstep/subway/domain/DefaultFarePolicy.java
> +    public DefaultFarePolicy(int fare) {
기본 요금을 1250이 아닌 다른 값으로 하고 싶을 때, 쓰기 위한 목적으로 만들었습니다.
지금 미션에서는 큰 의미가 없긴 한 것 같네요.

2022-02-23 03:01 UTC, soosue commented on src/test/java/nextstep/subway/unit/DefaultFarePolicyTest.java
> +    void apply() {
apply했을 때, 기본요금이 반환되는가를 검증하고 싶었습니다.
기본 요금의 유효성에 대해서 검사를 해보라는 말씀일까요?

2022-02-24 07:59 UTC, kang-hyungu commented
> 피드백 적용해봤는데 한 번 확인해주시면 감사하겠습니다. `SubwayFare.calculate()`의 로직을 어떻게 하면 좋게 짤 수 있을지 감이 잘 오지 않네요.

코드가 훨씬 간결해져서 좋네요.
매직넘버만 어떤 정책인지 의미 있는 이름을 붙여주면 더 좋을 것 같습니다.

2022-02-24 07:59 UTC, kang-hyungu approved these changes
윤수님 피드백 반영 잘 해주셨습니다.
pr은 머지 처리하겠습니다. 수고하셨어요.

2022-02-24 08:00 UTC, merged