Mission3 리뷰 요청드립니다~
next-step/atdd-subway-fare pull request #136
Opened 2022-02-25 03:37 UTC by MrPPak

마지막 미션이네요 이번에도 리뷰 잘부탁드립니다!

2022-02-27 16:01 UTC, heesunjeong requested changes
3단계 미션 요구사항도 잘 구현해주셨네요 👍 
몇가지 조금 더 고려해보시면 좋을 것 같은 부분에 코멘트를 남겨두었으니 확인 부탁드려요~!
이제 미션이 끝나가고 있네요~! 마지막까지 화이팅입니다 🔥 🔥 🔥

2022-02-28 04:20 UTC, MrPPak commented on src/main/java/nextstep/subway/auth/authorization/AuthenticationPrincipalArgumentResolver.java
> +        }
옵션을 추가하는 방법에 대해 구글링을 하였는데 잘 나오지 않아서요.. 혹시 예시나 자료를 부탁드려도 될까요??

2022-02-28 04:21 UTC, MrPPak commented on src/main/java/nextstep/subway/line/domain/Sections.java
>  }
말씀 주신대로 디미터 방식을 적용하여 코드를 짜봤습니다 :)

그런데 이 경우에 저는 전의 방식과 큰 차이를 못느꼈는데요 왜냐면 이렇게 짜도 Line이 바뀐다면 이 부분도 수정을 해야하기 때문입니다. 이렇게 바꿨을 때 장점이 궁금합니다!

2022-02-28 04:22 UTC, MrPPak commented on src/main/java/nextstep/subway/path/domain/DistancePolicy.java
> +        private static final int BASE_MAX_FARE = 1250;
혹시 Fare에 상수를 추가하시라는 말씀이실까요??

2022-03-01 01:52 UTC, heesunjeong approved these changes
종혁님 피드백 반영 잘 해주셨어요 ! 👍 
추가로 질문 주신 부분과 몇 가지를 코멘트로 남겼는데요, 확인 부탁드려요 :) 궁금하신 점이나 다른 의견은 편하게 코멘트 남겨주세요!
이번 단계는 머지하도록 하겠습니다~! 미션 마지막까지 완주하시느라 고생 많으셨어요 👏 👏 
이번 과정을 통해서 ATDD, TDD를 경험해보고 많은 인사이트를 얻어가시는 기회가 되셨기를 바랍니다 🔥 🔥

2022-03-01 01:52 UTC, merged