1단계 - 경로 조회 타입 추가
next-step/atdd-subway-fare pull request #166
Opened 2022-08-07 07:21 UTC by artium59

### Summary
기능 요구사항 - 최소 시간 경로 타입 추가
- 경로 조회 시 최소 시간 기준으로 조회할 수 있도록 기능을 추가하세요.
- 노선추가 & 구간 추가 시 거리와 함께 소요시간 정보도 추가하세요.
- 인수 테스트 (수정) -> 문서화 -> 기능 구현 순으로 진행하세요.
- 개발 흐름을 파악할 수 있도록 커밋을 작은 단위로 나누어 구현해보세요.

### Comment

2022-08-08 00:02 UTC, testrace requested changes
안녕하세요 승재님 😃 
리뷰를 맡게된 송용주입니다.

1단계 미션 잘 수행해 주셨네요 👍 
요구사항의 의도대로 TDD 진행을 확인할 수 있게 커밋 단위를 작게 나누는 경험을 해보시길 추천드립니다!
TODO LIST를 작성해서 구현할 내용을 정리한다면 커밋 단위를 작게 나누는데 도움이 되실 것 같아요.

소소하게 코멘트 남겨두었으니 확인해 주시고 리뷰 요청 부탁드립니다.
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-08-08 00:02 UTC, testrace commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> +    }
enum으로 최단거리와 소요시간을 구분해 주셨네요 👍 
열거 타입에 따라 결정되는 로직이라면 SearchType 내부로 로직을 옮겨 보시면 어떨까요?

2022-08-08 00:02 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
>      }
공통 부분을 추상화해서 별도의 메서드로 만들어 활용해 볼 수 있을 것 같아요 😃

2022-08-08 00:02 UTC, testrace commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +                .then().log().all().extract();
문서화 테스트에서도 중복 부분이 발생하는데요
인수테스트처럼 Stpes를 활용해 중복 제거를 할 수 있지 않을까요?

2022-08-08 00:02 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineServiceTest.java
> +
불필요한 import는 삭제해 주세요 😃

2022-08-08 00:02 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        line.addSection(역삼역, 삼성역, 5, 2);
필드 하나가 변경되어서 테스트에서 중복되는 변경이 계속 일어나게 되면 중복 제거를 해야하는 부분임을 인지할 수 있습니다.
이런 경우에는 변경을 수행하기 전에 중복 제거를 먼저 해준다면 지금보다 적은 양의 코드 수정이 가능하지 않았을까요?

2022-08-08 00:02 UTC, testrace commented on src/test/java/nextstep/subway/unit/SubwayMapTest.java
> +    void findPathByDuration() {
Displayname을 추가해서 테스트의 의도를 조금 더 명확하게 전달하면 좋을 것 같아요 😃

2022-08-08 15:29 UTC, artium59 commented
전체적으로 리뷰를 반영했습니다만, `name 메서드로 이름을 꺼내어 비교를 하기 보다 메시지를 보내면 어떨까요?`를 이해하지 못했습니다. 더 설명 부탁드려도 될까요.

2022-08-09 01:49 UTC, testrace approved these changes
안녕하세요 😃 
피드백 반영 잘해 주셨네요 💯

다음 단계에서는 프로그래밍 요구사항에 맞춰서 커밋 단위를 작게 나누어서 진행해 보셨으면 합니다
인수 테스트 주도 개발 프로세스 경험으로 많은 인사이트를 얻으실 수 있을거라 생각합니다!

질문에 대한 답변은 코멘트로 남겨두었으니 확인해 주시고 다음 단계 진행해 주세요 🔥 
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-08-09 01:49 UTC, testrace commented on src/main/java/nextstep/SearchTypeConverter.java
> +                .filter(s -> s.getCriteria().equalsIgnoreCase(source))
질문 주셨던 부분이네요.
이 로직은 SearchType의 criteria와 동일한지 비교를 하고 있는데요, getter를 이용해 꺼내면 서 비교하지 않고
SearchType에게 동일한 이름을 가졌는지 메시지를 보내면 Converter 객체가 직접 비교하지 않아도 됩니다.

비교 로직을 SearchType 내부로 옮기면 Converter에서는 아래와 같은 코드로 변경할 수 있을 것 같아요 
```suggestion
                .filter(s -> s.isSameCriteria(source))
```
피드백 드린 의도는 디미터 법칙을 지켰으면 해서 입니다.
자세한 내용은 [디미터 법칙](https://johngrib.github.io/wiki/law-of-demeter/)을 참고해 보시면 좋을 것 같아요

2022-08-09 01:49 UTC, testrace commented on src/main/java/nextstep/subway/constant/SearchType.java
> +    private final Function<Section, Integer> edgeWeight;
Function 활용 👍 
지하철 노선과 관련된 도메인에서 `weight`라는 용어가 적합한지도 고민해 보시면 좋을 것 같아요

2022-08-09 01:49 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    private ExtractableResponse<Response> searchType에_따른_두_역의_최단_경로_조회를_요청(Long source, Long target, SearchType searchType) {
피드백 반영 👍

2022-08-09 01:50 UTC, testrace commented on src/test/java/nextstep/subway/unit/SubwayMapTest.java
>      @Test
여기에도 displayname이 있으면 좋을 것 같아요

2022-08-09 01:51 UTC, merged