🚀 2단계 - 요금 조회
next-step/atdd-subway-fare pull request #172
Opened 2022-08-08 05:35 UTC by defianz

안녕하세요~ 2단계 미션도 구현해봤습니다.

미션 조건 중에
```
인수 테스트 (수정) -> 문서화 -> 기능 구현 순으로 진행하세요.
```
로 나온 내용이 있는데요! 

혹시 문서화를 진행해보라는게 어떤건지 설명해주실 수 있으실까요?
1단계에서 진행한 문서화 작업 이후, 추가적으로 필요한 문서화 진행 내용이 있는지 궁금합니다.

리뷰 잘 부탁드리겠습니다 감사합니다. 🙇🏻‍♂️

2022-08-09 04:21 UTC, starkim06 requested changes
안녕하세요!!!

2단계도 요구사항에 맞게 잘 구현해주셨네요!
질문에 대한 답변과함께 코멘트 몇가지 달아두었는데요 확인 부탁드립니다!

2022-08-09 07:11 UTC, defianz commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +                () -> assertThat(response.jsonPath()
요고는 모르는 표현이였는데 알게되었네요..! ([링크](https://countryxide.tistory.com/52))
좋은 리뷰 감사합니다~

2022-08-09 07:17 UTC, defianz commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        Assertions.assertAll(
막연히 bulk 로 체크한다고 생각했는데,
[assertAll vs assertThat](https://stackoverflow.com/questions/40796756/assertall-vs-multiple-assertions-in-junit5) 을 찾아보니, 순서대로 실행하는 단일 assertions 과 달리 모든 assertions를 실행하여 어떤것이 실패했는지 한번에 볼 수 있는 장점이 있는것 같습니다~

2022-08-09 08:39 UTC, defianz commented on README.md
> +- [x] 인수 테스트 (수정) -> 문서화 -> 기능 구현 순으로 진행하세요.
네 이건 아래와 같이 만들어서 갱신했습니다~ 👍|
![image](https://user-images.githubusercontent.com/18758041/183604623-4c708e9c-893e-4a27-8759-ed8158580b9c.png)

2022-08-09 08:39 UTC, defianz commented on src/test/java/nextstep/subway/unit/FareCalculatorTest.java
> +    void calculate_9km_fare() {
네 반영했습니다~!

2022-08-10 07:20 UTC, starkim06 approved these changes
안녕하세요!! 

전체적으로 리팩토링 잘 진행해주신것 같아요!!
미션 진행하시면서 잘 이해가지 않는 요구사항은 바로 말씀주세요!!
다음 단계 진행 부탁드려요!

2022-08-10 07:20 UTC, merged