2단계 - 요금 조회
next-step/atdd-subway-fare pull request #174
Opened 2022-08-08 11:45 UTC by zbqmgldjfh

## 안녕하세요 리뷰어님!
리뷰를 받게된 김지우 라고 합니다! 저의 리뷰를 담당해주셔서 감사합니다!

2022-08-08 11:46 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        int shortestDistance = subwayMap.findShortestPathDistance(upStation, downStation);
최단 거리를 찾는 부분이 뭔가 썩 마음에 들지는 않습니다.
리뷰어님이라면 어떻게 개선하실지 의견 궁굼합니다!

2022-08-08 23:36 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> +        return path.extractDistance();
너무 Initiator를 계속 생성하게 되는것 같기도 해서 고민입니다.
아예 Bean으로 등록해버리는것이 좋을까요?

2022-08-09 03:45 UTC, 00hongjun requested changes
2단계도 잘 진행해 주셨네요 👍 
몇 가지 코멘트를 달아두었는데 확인 부탁드립니다!

2022-08-09 03:47 UTC, 00hongjun commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        int shortestDistance = subwayMap.findShortestPathDistance(upStation, downStation);
요금은 최단거리를 기준으로만 구하고 있는데요.
최단거리, 최소 시간 별로 경로를 구하고 해당 경로의 요금을 구해주어야 할 것 같아요.
기능 리팩토링을 하면 경로를 2번 구하는 로직이 수정될 것 같아 보이네요 😃

2022-08-09 03:49 UTC, 00hongjun commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> +        return path.extractDistance();
bean으로 등록된다면 상태를 가지고 있지 않아야 하는데 고민해 본 방법이 있으신가요?

2022-08-09 23:43 UTC, zbqmgldjfh commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        int shortestDistance = subwayMap.findShortestPathDistance(upStation, downStation);
말씀해주신 것처럼 Path 자체에 필드를 갖도록 하는 방식으로 수정하였습니다!

2022-08-09 23:43 UTC, zbqmgldjfh commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        var response = 두_역의_최단_시간_경로_조회를_요청(교대역, 양재역);
var를 사용한 이유는 인수테스트는 가독성이 우선시 된다 생각하기 떄문입니다.
또한 개발자가 아닌, 기획자나 디자이너 분들도 볼 수 있기 때문에 인수테스트 자체의 가독성을 높혔습니다 ㅎㅎ
ExtractableResponse<Response> 이라는 타입을 개발자 외의 분들이 알필요는 없다 생각했기 때문입니다.

2022-08-09 23:43 UTC, zbqmgldjfh commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +        given(pathService.findShortestPath(anyLong(), anyLong(), any())).willReturn(pathResponse);
음 우선 추천해주신 방법에 대하여 문서의 좋은 관리방법이라 생각됩니다.

다만, 저희의 미션 요구사항에서 ATDD 사이클은
"인수테스트 작성 -> 문서작성 -> TDD로 개발" 사이클 순 입니다. 
따라서 내부 구현이 되있지 않은 상황에서 문서를 먼저 작성해야 하는데, 
이때 mock없이 실제 객체의 사용을 힘들것 같다 생각됩니다.

물론 TDD로 기능 개발을 다 한 후, 문서화를 할수도 있지만, 먼저 문서화를 하자는 취지에 어긋난다 생각됩니다 ㅠ,ㅠ

2022-08-10 11:55 UTC, 00hongjun commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +        given(pathService.findShortestPath(anyLong(), anyLong(), any())).willReturn(pathResponse);
넵 저도 개발과정에서는 mock을 애용합니다 😃
다만, 버전 관리에 들어간 API들은 mock 보다는 실제 객체들을 이용하도록 처리해 보고 있어요.
제가 의미 전달이 잘못되게 코멘트를 작성한 것 같네요.

2022-08-10 11:56 UTC, 00hongjun approved these changes
고생하셨습니다 지우님
머지 하도록 할게요. 다음 단계로 넘어가시죠  😃

2022-08-10 11:57 UTC, merged