2단계 - 요금 조회
next-step/atdd-subway-fare pull request #181
Opened 2022-08-09 08:42 UTC by artium59

### Summary
- 경로 조회 결과에 요금 정보를 포함하세요.
- 인수 테스트 (수정) -> 문서화 -> 기능 구현 순으로 진행하세요.
- 개발 흐름을 파악할 수 있도록 커밋을 작은 단위로 나누어 구현해보세요.

### Comment
- 요금 계산이 간단히 거리로만 계산해서 `PathResponse.java` 안에 구현하였는데, 3단계 보니까 분리해야겠네요.

2022-08-10 07:38 UTC, testrace requested changes
안녕하세요 😃 

단순히 기능을 구현하는 것을 목적으로 하기 보다 
미션의 취지에 맞게 인수 테스트 주도 개발 프로세스를 경험하는 것이 중요하다고 생각합니다.

관련된 코멘트 남겨두었으니 확인해 주시고 리뷰 요청 부탁드립니다.
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-08-10 07:38 UTC, testrace commented on src/test/java/nextstep/subway/applicaion/dto/PathResponseTest.java
> +    }
경계값 테스트 👍 
ParameterizedTest를 활용해 보시는 것도 좋을 것 같아요

2022-08-10 15:08 UTC, artium59 commented
요금과 관련된 인수 테스트를 작성하면 어떨까요?
- 지금은 요금이 거리에 종속되어 있어서 필요하지 않다고 생각합니다. 3단계에서 노선 별 추가요금이 붙는 것으로 아는데, 만약 '최소 요금으로 갈 수 있는 경로를 알려주는 api'가 필요하다면 그 때 만들 것 같습니다.

ParameterizedTest를 사용해보려 했는데, 뭔가 마음에 들지 않습니다.
- `50km = 10km + 40km = 기본_요금 + ceil(40/5)*100`를 표현하기 위해서 일부러 `기본_요금 + 800`으로 하였고, Arguments를 쓰자니 거리 별로 test를 나누었기 때문에 3개가 필요해서 별로라 생각했습니다.

2022-08-11 09:04 UTC, testrace requested changes
안녕하세요 😃 
피드백 반영 잘해 주셨네요 👍 

한 가지 확인하고 싶은 부분이 있어서 코멘트 남겨두었으니
확인해 주시고 리뷰 요청 부탁드립니다.

2022-08-11 13:09 UTC, artium59 commented
요금 계산을 담당하는 객체를 domain이 아닌 application 패키지로 설정하신 이유가 궁금합니다
- domain이랑 같은 layer에 두려고 했는데, 실수했습니다.
- domain으로 dto를 만드는데 domain에 두는 것은 이상하다고 생각합니다.

Builder 라는 이름도 생성 패턴을 떠올리는 이름이라 요금 계산 기능이 포함될거라고 생각하기 힘들지 않을까 싶습니다.
- Builder여서 더 직관적이라 생각합니다. PathResponse는 이 객체를 통해서만 만드는 것을 의도하였고요, 아직까진 path 안의 정보로도 충분히 만들 수 있다고 생각합니다.
- PathService에서 여러 곳에서 정보를 가져와 new로 만드는 것 보다, builder에서 정보를 가저오는 것이 더 낫다고 생각했습니다.

2022-08-11 23:50 UTC, testrace approved these changes
안녕하세요 😃 
피드백 반영 잘해 주셨네요 💯
바로 다음 단계 진행해 주세요 🔥

2022-08-11 23:50 UTC, merged