🚀 2단계 - 요금 조회
next-step/atdd-subway-fare pull request #191
Opened 2022-08-11 07:04 UTC by shinseongsu

merge 하지 않고 진행하다 보니.. 커밋 메시지가 겹친것같아요 😢 

2단계 미션 요금 조회 진행하였습니다
너무 늦게 보내 죄송합니다 😭

2022-08-11 23:36 UTC, 00hongjun requested changes
안녕하세요 :)
몇 가지 코멘트를 달아두었습니다!
확인 후 다시 한번 리뷰 요청 주세요!

2022-08-13 06:39 UTC, shinseongsu commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
>       * *3호선(2, 10)*                     *신분당선* (10, 1)
아 그렇군요 환승하는 구간인데 DisplayName을 잘 못 썼네요 😄

2022-08-13 06:39 UTC, shinseongsu commented on src/test/java/nextstep/subway/unit/PathTest.java
> +    }
네 알겠습니다~

2022-08-13 06:40 UTC, shinseongsu commented on src/main/java/nextstep/subway/domain/Path.java
> +    }
pricepolicy 같은 요금 정책 class를 하나 만들어 사용하는게 더 좋아보이네요 😄  👍

2022-08-13 06:40 UTC, shinseongsu commented on src/main/java/nextstep/subway/domain/Path.java
> +    }
아 최소시간도 최단거리 기준의 요금을 반환해야 하는군요 제가 요구사항을 잘 못 파악한것같네요

2022-08-13 08:03 UTC, shinseongsu commented
- [x] 최소시간 경로도 최단거리 경로 요금으로 계산
- [x] 기본 요금 및 추가요금 테스트 코드 추가
- [x] 요금 정책 메소드 분리

2022-08-14 03:07 UTC, 00hongjun approved these changes
안녕하세요 성수님
리뷰 반영 잘 진행해 주셨네요 👍 
머지 하도록 하겠습니다. 다음 단계로 넘어가시죠 🚀

2022-08-14 03:07 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/DistancePricePolicy.java
> +public class DistancePricePolicy implements PricePolicy {
DistancePricePolicy가  추가되었네요 👍

2022-08-14 03:07 UTC, 00hongjun commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        int shortestDistance = subwayMap.findPath(upStation, downStation, PathType.DISTANCE.getEdgeInitiator()).extractDistance();
'최단거리' 기준으로 경로 조회 요청이 왔을 경우
`subwayMap.findPath()`내부에서 사실상 같은 로직이 중복으로 2번 일어나게 되는데요.
조금 더 효율적으로 변경할 수 없을지 고민해 보면 어떨까요?🤔

2022-08-14 03:08 UTC, merged