step2 - 요금 조회
next-step/atdd-subway-fare pull request #212
Opened 2022-08-14 12:13 UTC by zzangoobrother

안녕하세요.
이번 리뷰도 잘 부탁드립니다!
감사합니다~

2022-08-15 10:27 UTC, starkim06 requested changes
안녕하세요!!

이번 단계도 요구사항에 맞게 잘 구현해주셧네요!!
간단한 코멘트 몇가지 남겨두었습니다!
확인 부탁드려요 =)

2022-08-15 10:27 UTC, starkim06 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void 두_역_최단_거리_경로_조회() {
DisplayName에서 이렇게 변경하신 이유가 있을까요?

2022-08-15 10:27 UTC, starkim06 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +            () -> assertThat(response.jsonPath().getInt("fare")).isEqualTo(1250)
정수를 표현할때 3자리씩 끊어서 1_250 와 같이 표현하면 조금 더 읽기 편할것 같아요

2022-08-15 10:27 UTC, starkim06 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        assertAll(
assertAll을 사용하면 어떤 장점이 있을까요?

2022-08-15 10:27 UTC, starkim06 commented on src/test/java/nextstep/subway/unit/FareCalculatorTest.java
> +  void 요금_계산_10KM_이내() {
경계값을 검사하는것도 좋을것 같아요!

2022-08-15 10:27 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/path/finder/FareCalculatorRule.java
> +  private static final int BASICFARE = 1250;
BASIC_FARE로 구분해주시면 조금 더 읽기 편할것 같아요

2022-08-15 10:27 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/path/finder/FareCalculatorRule.java
> +  private static final int ONE = 1;
ONE과 같은 경우는 별도의 상수로 만들지 않아도 충분히 의미가 이해 가능하다고 생각하는데 어떻게 생각하시나요?

2022-08-15 10:27 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/path/finder/FareCalculatorRule.java
> +public class FareCalculatorRule {
Rule 클래스로 별도로 분리하지 않아도 괜찮다는 생각도 드는것 같아요. 
지금과 같은 상황이면 요금 구간의 기준이 10에서 15와 같이 바뀐다면 FareCaculator클래스와 이 클래스 모두 수정해줘야 될 것 같아요

2022-08-15 10:27 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/Section.java
> +    public int getWeight(PathType pathType) {
이런 경우에 PathType에 새로운 타입이 추가되었을 때 getDuration return할 실수의 여지가 있을 것 같아요. 각각의 케이스를 조건문으로 하고 나머지 케이스에서는 예외를 던져보는건 어떨까요?

2022-08-15 10:27 UTC, starkim06 commented on src/main/java/nextstep/subway/domain/path/finder/PathDistanceFinder.java
> +    super(lines);
이제는 이 클래스들이 의미가 많이 없는것처럼 보여요

2022-08-15 10:27 UTC, starkim06 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +            () -> assertThat(response.jsonPath().getList("stations.id", Long.class)).containsExactly(교대역, 남부터미널역, 양재역),
assertAll 내부의 4가지 값에 대한 검증이 이 테스트 클래스에 다 있는것 같은데 중복제거를 해보시는건 어떨까요?

2022-08-15 10:47 UTC, zzangoobrother commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void 두_역_최단_거리_경로_조회() {
한글로 통일하면 관리하기도 편하고 프로젝트를 한다면 다른 사람들과 소통이 원활하기 때문에 변경했습니다.

2022-08-15 10:52 UTC, zzangoobrother commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        assertAll(
assertAll 사용 전에는 테스트가 틀린 곳을 하나씩 로직 순서대로 확인 가능하지만 assertAll 사용하면 assertAll 내부 전체 확인할 수 있어 고칠 때 한 번에 고칠수 있어 좋았습니다.

2022-08-16 14:18 UTC, starkim06 approved these changes
안녕하세요!! 

리팩토링 전체적으로 잘 해주신것 같아요!! 
다음단계도 진행 부탁드려요!!

2022-08-16 14:19 UTC, merged