[Step3] 리뷰 요청드립니다~~!
next-step/atdd-subway-fare pull request #216
Opened 2022-08-15 05:12 UTC by exemeedys

2022-08-15 12:51 UTC, pch8388 requested changes
안녕하세요 🙇 
3단계 미션 수행하시느라 고생 많으셨습니다 👏 
학습을 위해 조금만 더 힘을 내주세요 💪 
코멘트 남겨 드린 부분에 대해 수정 후 리뷰 요청 해주세요 🔥

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/support/auth/authorization/AuthenticationPrincipalArgumentResolver.java
> +            return new User();
[Null object pattern](https://johngrib.github.io/wiki/pattern/null-object/) 을 참고해보세요 😄

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                && request.getDistance() != 0 && request.getDuration() != 0) {
메서드 추출을 통해 세부사항을 감추면 더 좋을 것 같아요

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +import javax.naming.OperationNotSupportedException;
쓰지 않는 `import`는 삭제해주세요

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        if(!pathStrategyMap.containsKey(type)) {
이 검증이 `service` 에서 이루어져야 할 지 고민해보면 좋을 것 같아요 😅 
하지만 현재 구조로는 어떤 타입을 받을 수 있는 지는 `Service` 에서만 확인이 가능한데, enum 같은걸 활용해봐도 좋을 것 같아요

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +            Member member = memberService.findByEmail(user.getUsername());
이 Member 의 정보에 결국 필요한 건 `age` 인데, CustomUserDetailsService 에서 정보를 넣어주는 건 어떨까요? 🤔

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/discount/DiscountCalculator.java
> +        TODDLER(age -> age <6),
의미를 가질 수 있는 리터럴은 이름을 부여하는 것이 표현력이 더 좋은 것 같아요
> 클린 코드 G25: 매직 숫자는 명명된 상수로 교체하라

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/discount/DiscountCalculator.java
> +    TODDLER_POLICY(TODDLER, fare -> fare),
유아는 요금을 `무료`로 해주시면 됩니다 😄

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/Price.java
> +public class Price {
다른 곳에서는 요금에 대해 `fare` 로 표현하셨는데 여기선 `price`로 표현하셨네요 💭 
이유가 있을까요?

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/fare/BasicFarePolicy.java
>          return (long) ((Math.ceil((distance - 1) / 5) + 1) * 100);
계산하는 부분도 리팩터링이 가능할 것 같아요 😢

2022-08-15 12:51 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +            fare = DiscountCalculator.applyToDiscountFare(DiscountCalculator.DiscountPolicy.get(member), fare);
또다른 할인 정책이 추가되었을 때는 어떻게 처리할 수 있을까요? 🤔

2022-08-15 12:51 UTC, pch8388 commented on src/test/java/nextstep/subway/unit/FarePolicyTest.java
> +    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
👍 
모든 값을 다 테스트 하기보다는 경계에 있는 값들에 대해 테스트하시면 될 것 같아요

2022-08-16 10:14 UTC, eedys1234 commented on src/test/java/nextstep/subway/unit/FarePolicyTest.java
> +    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
넵!

2022-08-16 10:20 UTC, eedys1234 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +            fare = DiscountCalculator.applyToDiscountFare(DiscountCalculator.DiscountPolicy.get(member), fare);
방문자 패턴 or 컴파운드 패턴을 적용하는 방안을 통해 확장성 있게 설계하는 방법이 생각났습니다. 조금 더 생각해볼께요~

2022-08-16 10:21 UTC, eedys1234 commented on src/main/java/nextstep/subway/domain/Price.java
> +public class Price {
크게 이유가 없습니다. Fare로 통일하는게 좋을 듯하네요

2022-08-16 10:21 UTC, eedys1234 commented on src/main/java/nextstep/subway/domain/discount/DiscountCalculator.java
> +    TODDLER_POLICY(TODDLER, fare -> fare),
넵!

2022-08-16 10:21 UTC, eedys1234 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        if(!pathStrategyMap.containsKey(type)) {
넵!

2022-08-16 10:21 UTC, eedys1234 commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                && request.getDistance() != 0 && request.getDuration() != 0) {
넵!

2022-08-16 10:21 UTC, eedys1234 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +import javax.naming.OperationNotSupportedException;
네!

2022-08-16 10:21 UTC, eedys1234 commented on src/main/java/nextstep/subway/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AuthenticationPrincipal User user,
음....네!

2022-08-16 12:41 UTC, exemeedys commented on src/main/java/nextstep/subway/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AuthenticationPrincipal User user,
> 음....네!
말씀하신대로 생각해보니 email 값이 null로 들어가 에러를 발생시킬 수 있을 것 같네요

2022-08-16 12:58 UTC, exemeedys commented on src/main/java/support/auth/authorization/AuthenticationPrincipalArgumentResolver.java
> +            return new User();
넵!

2022-08-16 15:13 UTC, exemeedys commented on src/main/java/nextstep/subway/applicaion/LineService.java
> +                && request.getDistance() != 0 && request.getDuration() != 0) {
넵!

2022-08-16 15:13 UTC, exemeedys commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +import javax.naming.OperationNotSupportedException;
넵!

2022-08-16 15:13 UTC, exemeedys commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        if(!pathStrategyMap.containsKey(type)) {
넵!

2022-08-16 15:13 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/discount/DiscountCalculator.java
> +    TODDLER_POLICY(TODDLER, fare -> fare),
넵!

2022-08-16 15:13 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/Price.java
> +public class Price {
크게 이유가 없습니다. Fare로 통일하는게 좋을 듯하네요

2022-08-16 15:14 UTC, exemeedys commented on src/test/java/nextstep/subway/unit/FarePolicyTest.java
> +    @ValueSource(ints = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10})
넵!

2022-08-16 15:14 UTC, exemeedys commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +            fare = DiscountCalculator.applyToDiscountFare(DiscountCalculator.DiscountPolicy.get(member), fare);
방문자 패턴 or 컴파운드 패턴을 적용하는 방안을 통해 확장성 있게 설계하는 방법이 생각났습니다. 조금 더 생각해볼께요~

2022-08-16 15:14 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/fare/BasicFarePolicy.java
>          return (long) ((Math.ceil((distance - 1) / 5) + 1) * 100);
넵!

2022-08-17 12:47 UTC, pch8388 approved these changes
리팩터링 잘해주셨습니다 👏 
코멘트 드린 부분들에 대해 참고만 해주시면 될 것 같습니다 😄 
이번 미션은 마무리하겠습니다 고생많으셨습니다

2022-08-17 12:47 UTC, pch8388 commented on src/main/java/nextstep/subway/domain/path/PathStrategies.java
> +    DURATION("DURATION",section -> section.getDuration());
아래와 같이 표현하는 것도 좋은 것 같아요 😄 
```suggestion
    DISTANCE("DISTANCE", Section::getDistance),
    DURATION("DURATION", Section::getDuration);
```

2022-08-17 12:47 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        long fare = path.calculateFare();
FarePolicy 와 DiscountPolicy 를 통합하는 방법은 없을까요? 🤔 
`요금을 계산한다`라는 행위 자체로 일반화 시킬수도 있을 것 같아요 😄 
FarePolicy 와 DiscountPolicy 가 의존성 주입되는 방법도 다르고, 계산도 따로 하는 것이 조금 어색해보이는 데 어떻게 생각하시나요?

이 부분은 추후 개선 포인트로 고민해보시면 좋을 것 같아요 🔥

2022-08-17 12:47 UTC, pch8388 commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    }
이 메서드를 DTO 가 가지는게 맞을까요?
DTO 가 로직을 가지고, Service 가 해당 로직에 의존하는 형태는 높은 결합도가 생기는 결과를 발생시킬 수 있을 것 같아요 😢

2022-08-17 12:47 UTC, merged

2022-08-17 13:18 UTC, exemeedys commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        long fare = path.calculateFare();
네!

2022-08-17 13:18 UTC, exemeedys commented on src/main/java/nextstep/subway/domain/path/PathStrategies.java
> +    DURATION("DURATION",section -> section.getDuration());
넵!

2022-08-17 13:18 UTC, exemeedys commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    }
음...수정해보겠습니다.