🚀 3단계 - 요금 정책 추가
next-step/atdd-subway-fare pull request #223
Opened 2022-08-15 18:20 UTC by shinseongsu

## 기능 요구사항
- [x] 추가된 요금 정책을 반영하세요.
- [x] 인수 테스트 변경 -> 문서화 변경 -> 기능 구현 순으로 진행하세요.
- [x] 개발 흐름을 파악할 수 있도록 커밋을 작은 단위로 나누어 구현해보세요.

-> 코멘트로 주신 최단 거리할때 중복 사용되는 코드도 수정 하였습니다.

2022-08-16 06:54 UTC, 00hongjun requested changes
안녕하세요 성수님
몇 가지 코멘트를 작성해두었습니다!
확인 후 다시 한번 리뷰 요청 주세요 😃

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/discount/ChildDiscountPolicy.java
> +        return age >= 6 && age < 13;
6, 13의 의미를 상수로 표현해 보면 어떨까요? 🤔

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/distance/DistancePricePolicy.java
> +import org.springframework.stereotype.Component;
사용되지 않는 import는 제거해 주세요 😃

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/ui/PathController.java
> +          @RequestParam Long target
경로 조회 API의 경우 로그인 유저, 비로그인 유저가 모두 사용 가능해야 할 것 같은데요.
수정해서 로그인, 비로그인 모두 사용 가능해 보도록 수정해 보면 좋을 것 같습니다 😃

인수테스트도 추가되면 좋을 것 같아요!

2022-08-16 06:54 UTC, 00hongjun commented on src/test/java/nextstep/subway/unit/DiscountPolicyTest.java
> +    }
경계값까지 테스트 잘 처리해 주셨네요 👍

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/PricePolicyService.java
> +    private Integer addtionPrice;
Service라는 이름은 스프링에서 보편적으로 `@Service`로 선언된 경우 많이 사용하다 보니
코드를 읽는 입장에서 오해를 불러올 수 있을 것 같아요.
다른 이름으로 변경해 보는건 어떨까요? 😃

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/PricePolicyService.java
> +    }
주석을 이용하는 것보단, 메서드의 이름으로 행위를 표현하도록 수정하면 좋을 것 같습니다.

거리, 나이별 할인은 해당 메서드에서 처리하지만, 추가요금은 생성자에서 받는 부분의 흐름이 어색해 보이는데 수정해 보면 어떨까요?

2022-08-16 06:54 UTC, 00hongjun commented on src/test/java/nextstep/subway/unit/PricePolicyServiceTest.java
> +    int 어른 = 19;
별것 아니지만.
미션에서는 '어린이', '청소년'으로 표기하고 있는데요.
문제 해결 영역인 만큼 동일한 언어를 사용해서 처리하면 이해관계자들과의 의사소통에서 오해를 줄일 수 있을 것 같습니다 😃

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
tdd 방식으로 진행되었다면 해당 도메인의 테스트 코드가 생성되었을 것 같습니다.
테스트 코드를 추가해 보면 어떨까요?

2022-08-16 06:54 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/discount/ChildDiscountPolicy.java
> +    }
코드가 짧아 사소해 보이지만
비즈니스에는 큰 영향을 미치는 도메인이라고 생각 드는데요.
테스트 코드를 추가해 보면 어떨까요?

2022-08-17 08:50 UTC, shinseongsu commented on src/main/java/nextstep/subway/price/discount/ChildDiscountPolicy.java
> +        return age >= 6 && age < 13;
넵 상수로 표시하도록하겠습니다 😄

2022-08-17 08:50 UTC, shinseongsu commented on src/main/java/nextstep/subway/price/distance/DistancePricePolicy.java
> +import org.springframework.stereotype.Component;
헉 제거가 안되었네요

2022-08-17 08:51 UTC, shinseongsu commented on src/main/java/nextstep/subway/price/PricePolicyService.java
> +    private Integer addtionPrice;
Service 메소드 이름을 수정하도록 하겠습니다 😄

2022-08-17 08:51 UTC, shinseongsu commented on src/main/java/nextstep/subway/price/PricePolicyService.java
> +    }
넵 알겠습니다 👍

2022-08-17 08:52 UTC, shinseongsu commented on src/test/java/nextstep/subway/unit/PricePolicyServiceTest.java
> +    int 어른 = 19;
기획을 잘 못 읽고 아이로 적었네요 별거 아니라고 생각해도 제가 그렇게 꼼꼼한 성격이 아니여서 ㅠㅠ 이런거 너무 좋습니다 👍

2022-08-17 08:53 UTC, shinseongsu commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
테스트 코드를 빠드렸네요 👍

2022-08-17 08:53 UTC, shinseongsu commented on src/main/java/nextstep/subway/price/discount/ChildDiscountPolicy.java
> +    }
이것도 테스트 코드 않넣었네요 ㅎㅎ 넣도록 하겠습니다

2022-08-17 09:21 UTC, 00hongjun approved these changes
안녕하세요 성수님
마지막 미션까지 마무리해 주셨네요.
그동안 미션 진행하느라 고생 많으셨습니다! 
미션은 머지하도록 하겠습니다 🙌

2022-08-17 09:21 UTC, 00hongjun commented on src/main/java/nextstep/subway/price/discount/ChildDiscountPolicy.java
> +    private static final double DISCOUNT_RATE = 0.5;
같은 의미를 가지는 상수들이 여러 곳에 선언되어 있는데요.
정책이 변경되었을 경우 수정해야 하는 코드들이 반복적으로 일어날 것 같아요 🤔
고민해 보시면 좋을 것 같습니다 😃

2022-08-17 09:21 UTC, 00hongjun commented on src/test/java/nextstep/subway/unit/AdultDiscountPolicyTest.java
> +public class AdultDiscountPolicyTest {
리뷰 반영 👍  테스트 코드가 더 보강되었네요

2022-08-17 09:21 UTC, 00hongjun commented on src/main/java/nextstep/subway/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AuthenticationPrincipal(isLogined = false) User user,
로그인, 비로그인 유저에 대한 처리가 추가되었군요 👍

2022-08-17 09:21 UTC, 00hongjun commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    private String 어린이;
사소한 부분까지 리뷰 반영 👍👍

2022-08-17 09:22 UTC, merged