Step2 - 요금조회
next-step/atdd-subway-fare pull request #226
Opened 2022-08-16 10:34 UTC by MaroKim

안녕하세요 송용주 리뷰어님 

교육생 김성태 입니다. 

먼저, 이전 과제에 대해 꼼꼼히 리뷰해주셔서 감사합니다. 

@parameterdTest는 리뷰어님 말씀듣고 찾아서 적용해봤는데 

단순 테스트를 간결하게 확인할 수 있어서 너무 좋았던것 같습니다. 새로운 방법을 제시해주셔서 감사합니다. 

이번 미션은 요금 정책 추가로 확인했습니다. 

근데 제가 긴가민가 했던건 인수조건에서는 최단거리 조회시에 요금을 계산하도록 되어 있어서 

실제로 최단거리로 조회 할때만 요금을 계산하고, 소요시간으로 검색을 할때는 요금을 계산하지 않도록 구성했습니다. 

제가 잘못이해하고 있는게 있다면 말씀해주시면 바로 고쳐 보겠습니다. 

이번 리뷰도 잘 부탁드리겠습니다!!

2022-08-16 12:33 UTC, testrace requested changes
안녕하세요 😃
2단계 미션 잘 수행해 주셨네요 👍 

질문에 대한 내용도 코멘트로 남겨두었으니 확인해 주시고 리뷰 요청 부탁드립니다.
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-08-16 12:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        return PathResponse.of(path, 0);
질문 주셨던 부분이네요!
최소 소요 시간으로 경로를 조회 하더라도 요금은 최단 거리 를 기준으로 계산이 되어야 합니다.
최소 소요 시간으로 경로를 구한 후에 최단 거리를 한 번 더 구해야 요금을 계산할 수 있겠네요

2022-08-16 12:33 UTC, testrace commented on src/main/java/nextstep/subway/domain/SubwayFare.java
> +            totalFare += calculateOverFare(overDistance, 5);
5, 8은 무슨뜻인지 알기 어려울 것 같아요
상수로 치환하여 의미를 부여하면 좋을 것 같아요 😃

2022-08-16 12:33 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    }
요금 관련 인수 테스트 👍

2022-08-16 12:33 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    }
이전 코멘트에서 말씀드렸지만, 시간으로 경로를 조회 하더라도 요금은 계산되어야 합니다
다만 시간으로 조회한 경로와 최단 경로는 다를 수 있고, 요금은 거리를 기준으로 계산되어야 합니다.

2022-08-16 12:33 UTC, testrace commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +                                        parameterWithName("type").description("조회 방식(최단 거리 : DISTANCE, 최소 소요 시간: DURATION)")
피드백 반영 감사합니다 😄

2022-08-16 12:33 UTC, testrace commented on src/test/java/nextstep/subway/unit/PathTypeTest.java
> +    }
DisplayName에 그냥 '값' 보다는 이전 테스트 코드처럼 '거리값' 이라고 명시해줘도 좋을 것 같아요
ParameterizedTest를 사용하셨으니 ParameterizedTest 의 name 속성을 활용해 보시면 좋을 것 같아요 😃

2022-08-16 12:33 UTC, testrace commented on src/test/java/nextstep/subway/unit/SubwayFareTest.java
> +    @CsvSource({"9,0", "46,800", "56, 900"})
ParameterizedTest를 사용할 때 source 값들은 개행을 통해 구분하는게 가독성이 도움이 되는 것 같아요 😃 
```suggestion
    @CsvSource({
        "9, 0", 
        "46, 800", 
        "56, 900"
    })
```

2022-08-16 12:33 UTC, testrace commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        SubwayFare subwayFare = new SubwayFare();
요금을 계산할 때 마다 SubwayFare 객체를 생성해야 하는데요, 1개의 객체만 만들어서 재활용하거나
SubwayFare는 상태를 가지고 있지 않으니 계산하는 메서드를 static으로 제공하는건 어떻게 생각하세요?

2022-08-16 23:43 UTC, MaroKim commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        return PathResponse.of(path, 0);
아 무슨 말씀인지 이해했습니다. 

감사합니다!

2022-08-16 23:43 UTC, MaroKim commented on src/main/java/nextstep/subway/domain/SubwayFare.java
> +            totalFare += calculateOverFare(overDistance, 5);
넵 알겠습니다~!

2022-08-16 23:44 UTC, MaroKim commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    }
넵 서비스 구현에 맞춰 변경하겠습니다.

2022-08-16 23:44 UTC, MaroKim commented on src/test/java/nextstep/subway/unit/PathTypeTest.java
> +    }
앗 속성이 더 있었군요

확인해보겠습니다. 감사합니다.

2022-08-16 23:45 UTC, MaroKim commented on src/test/java/nextstep/subway/unit/SubwayFareTest.java
> +    @CsvSource({"9,0", "46,800", "56, 900"})
아 개행이 가능한 부분이군요. 정보 감사합니다.

2022-08-16 23:47 UTC, MaroKim commented on src/main/java/nextstep/subway/applicaion/PathService.java
> +        SubwayFare subwayFare = new SubwayFare();
아 넵 맞습니다. 저도 저 부분이 좀 걸렸는데 수정해보겠습니다. 감사합니다

2022-08-17 08:54 UTC, testrace approved these changes
안녕하세요 😃 
피드백 반영 잘해 주셨네요 💯

소소한 코멘트 남겨두었으니 확인해 주시고 다음 단계 진행해 주세요 🔥 
궁금한 내용이 있으시면 편하게 DM 주세요!

2022-08-17 08:54 UTC, merged