[2단계 - 요금 조회] 리뷰 요청드립니다.
next-step/atdd-subway-fare pull request #242
Opened 2023-02-22 14:49 UTC by seondongpyo

안녕하세요, 형준님 👋 2단계 미션도 진행해봤습니다.
`FareCalculator`라는 클래스를 추가해서 요금을 계산하는 책임을 부여해봤는데
혹시 더 좋은 구조나 아이디어 있으시면 코멘트 부탁드리겠습니다.
이번 단계도 잘 부탁드립니다 🙏

2023-02-23 11:38 UTC, Flamme1004K requested changes
안녕하세요! 🙇🏻

2단계 미션 잘 구현해 주셨습니다! 💯

몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

2023-02-23 11:38 UTC, Flamme1004K commented on src/main/java/nextstep/subway/util/FareCalculator.java
> +public class FareCalculator {
FareCalculator는 도메인의 정책적인 부분이라고 생각해요. 과연 util 클래스가 맞을까요~?

2023-02-23 11:38 UTC, Flamme1004K commented on src/main/java/nextstep/subway/util/FareCalculator.java
> +    }
생성자는 필요 없을 것 같네요~

2023-02-23 11:38 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/FareCalculatorTest.java
> +    @MethodSource("calculateFareSource")
MethodSource를 사용한 테스트 👍👍 단, 요금 계산 방법에 따른 케이스로 테스트가 나뉘어지면 더 좋지 않았을까 생각이 드네요.

2023-02-23 11:38 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +            () -> assertThat(response.jsonPath().getInt("fare")).isEqualTo(1_450)
요금 계산 방법에 대한 여러가지 케이스에 대해서도 인수 테스트를 작성해볼까요?

2023-02-23 11:38 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/PathServiceMockTest.java
> +class PathServiceMockTest {
MockTest 반영 👍👍

2023-02-23 11:38 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/PathTest.java
> +class PathTest {
도메인 테스트 좋습니다 👍

2023-02-23 11:59 UTC, seondongpyo commented on src/main/java/nextstep/subway/util/FareCalculator.java
> +public class FareCalculator {
이 부분은 조금 더 고민해보겠습니다.

2023-02-23 12:00 UTC, seondongpyo commented on src/main/java/nextstep/subway/util/FareCalculator.java
> +    }
지금은 유틸리티 클래스다보니 인스턴스를 굳이 생성할 필요가 없어서 인스턴스 생성 방지차 추가했습니다.

2023-02-24 12:23 UTC, Flamme1004K approved these changes
안녕하세요! 🙇🏻

피드백 반영 잘 해주셨습니다! 💯 이만 머지하도록 하겠습니다.

다음 미션도 화이팅입니다. 응원하겠습니다! 🤩

2023-02-24 12:23 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    @DisplayName("지하철 구간 길이가 10km 초과 50km 이하라면, 기본 요금에 5km 마다 100원씩 요금이 추가된다.")
인수 테스트 👍👍

2023-02-24 12:23 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/Fare.java
> +public enum Fare {
도메인 패키지로 옮기셨군요! 👍👍

2023-02-24 12:23 UTC, Flamme1004K commented on src/test/java/nextstep/subway/unit/FareTest.java
> +class FareTest {
Fare에 대한 Unit테스트 👍

2023-02-24 12:23 UTC, merged