Step1: 경로 조회 타입 추가
next-step/atdd-subway-fare pull request #248
Opened 2023-02-24 16:54 UTC by hungrytech

Step1: 경로 조회 타입 추가 완료되어 리뷰요청 드립니다! 😄

2023-02-25 12:20 UTC, kang-hyungu requested changes
hungrytech님 몇 가지 코멘트 남겼습니다.
수정해보시고 리뷰 재요청주세요.

2023-02-25 12:20 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/Sections.java
> +                    upSection.get().getDistance() + downSection.get().getDistance(),
Section에 정적 팩터리 메서드를 추가해서 Section 객체를 생성해보는게 어떨까요?

그리고 파라미터로 Optional을 전달하는 것은 의도와 다르게 쓰이는 것이니 파라미터에서 optional을 제거해보시기 바랍니다.

![image](https://user-images.githubusercontent.com/15669435/221355854-23d4b26b-a70c-4a21-9fb8-089ed0d981ae.png)

2023-02-25 12:20 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> +    public Path findPath(Station source, Station target, PathSearchType pathSearchType) {
메서드가 너무 복잡한데요. 메서드를 10줄 이하로 줄여보면 좋겠네요.
중복 코드를 줄이고 적절한 책임을 가진 객체로 로직을 넘기는게 어떨까요?

2023-02-25 12:20 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> +            SimpleDirectedWeightedGraph<Station, SectionEdge> graph,
```suggestion
            WeightedGraph<Station, SectionEdge> graph
```

다형성을 활용해보면 어떨까요

2023-02-25 12:20 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/Path.java
> +    public int extractDuration() {
지금 Path 클래스는 단순하게 Sections의 메서드를 그대로 전달해주는 일만 하는데요.
Sections에서 거리를 계산하는 로직을 Path로 옮겨서 적절한 책임을 부여해주는게 어떨까요?

2023-02-25 12:20 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/Sections.java
>  }
Sections 클래스의 모든 메서드를 10줄이 넘어가지 않도록 작성해보시기 바랍니다.
중복 코드를 메서드로 추출하면 좀더 코드가 간결해질거에요.

2023-02-25 13:27 UTC, hungrytech commented on src/main/java/nextstep/subway/domain/Path.java
> +    public int extractDuration() {
Path 클래스가 Sections에게 자신이 가지고 있는 구간들에 대한 거리를 위임해도 좋을것 같다는 생각을 합니다.

Path는 경로 조회의 결과인 값객체라고 판단해도 좋지 않을까 생각이 들어서요 

리뷰어님 생각은 어떠신가요?

2023-02-25 13:38 UTC, hungrytech commented on src/main/java/nextstep/subway/domain/Sections.java
>  }
현재도 적절하게 나누어져있다고 생각이드는데 리뷰어님이 생각하시는 리팩토링할 부분들을 알 수 있을까요?

2023-02-25 14:37 UTC, hungrytech commented
리팩토링 완료했습니다. 

Path와 Sections 에 대한부분  리뷰해주신것에 대해서 코멘트 남겨놓았습니다. 확인해주시면 감사하겠습니다. 😄

2023-02-25 14:38 UTC, hungrytech commented
리팩토링 완료했습니다.

Path와 Sections 에 대한부분 리뷰해주신것에 대해서 코멘트 남겨놓았습니다. 확인해주시면 감사하겠습니다. 😄

2023-02-26 12:33 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/Path.java
> +    public int extractDuration() {
vo를 의도하신거라면 Sections에서 Path 객체를 생성하도록 만드는게 어떨까요?
지금은 Path가 단순 Sections 의 메서드 결과를 전달하는 일만 하고 있어서 혼란을 줄 것 같네요

2023-02-26 14:07 UTC, kang-hyungu commented on src/main/java/nextstep/subway/domain/Sections.java
>  }
stream을 단순화해보면 어떨까요. 예를 들면 foreach를 활용하거나 람다를 파라미터로 활용하여 거의 비슷한 형태의 stream을 줄이는 방법이 있겠네요.
```java
    private void checkDuplicateSection(Section section) {
        sections.forEach(it -> {
            // getter로 꺼내서 비교하지 말고 Section 객체 내부에서 직접 처리해야 캡슐화가 깨지지 않습니다.
            if (it.hasDuplicateSection(section)) {
                throw new IllegalArgumentException();
            }
        });
    }
```

```java
    private Station findFirstUpStation() {
        // stream을 너무 많이 쓰면 오히려 가독성을 해칩니다.
        List<Station> upStations = getStations(Section::getUpStation);
        List<Station> downStations = getStations(Section::getDownStation);
        downStations.forEach(upStations::remove);
        return upStations.get(0);
    }

    private List<Station> getStations(Function<Section, Station> mapper) {
        return this.sections.stream()
                .map(mapper)
                .collect(Collectors.toList());
    }
```

2023-02-26 14:07 UTC, kang-hyungu approved these changes
hungrytech님 피드백 반영 잘 해주셨습니다.
추가로 남긴 코멘트는 다음 단계 진행하면서 적용해보세요.
pr은 머지 처리하겠습니다. 수고하셨습니다.

2023-02-26 14:07 UTC, merged