2단계 - 요금 조회
next-step/atdd-subway-fare pull request #254
Opened 2023-02-25 16:09 UTC by codeleesh

안녕하세요, 홍준님

`2단계 - 요금 조회` 추가 리뷰 요청드립니다.

1단계 리뷰 요청 후 시간을 이용해서 2단계 - 요금 조회를 진행하고 있었습니다.

그럼, 소중한 리뷰 기다리고 있겠습니다.

감사합니다.

2023-02-26 13:25 UTC, hjhello423 requested changes
안녕하세요. 😀
step2도 잘 진행해 주셨네요. 👍
코멘트를 남겨두었는데 빠르게 해결 가능하실 것 같습니다!
다시 한번 리뷰 요청 주세요.

2023-02-26 13:38 UTC, codeleesh commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> -     */
네 인수 테스트 구현을 통한 메소드 네이밍을 을 통해 판단할 수 있다고 생각해서 해당 주석은 제거하였습니다.

2023-02-26 13:39 UTC, codeleesh commented
앗 해당 내용 리팩토링하다가 놓쳤습니다. 다시 수정해서 올렸습니다. 감사합니다.

2023-02-27 07:19 UTC, hjhello423 approved these changes
안녕하세요. 😀
step 2도 깔끔하게 마무리되었네요.
머지 하도록 하겠습니다.! 다음 step 진행해 주세요. 🔥

2023-02-27 07:19 UTC, hjhello423 approved these changes

2023-02-27 07:20 UTC, merged

2023-03-01 11:31 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/LineAcceptanceTest.java
> -     */
미션 요구사항에는 인수 조건을 메서드 상단에 주석으로 작성해 달라는 내용이 있어요 😀
![image](https://user-images.githubusercontent.com/15880709/222127355-b0c6ff0f-83ed-4b75-ac42-33f22d53c134.png)