1단계 - 경로 조회 타입 추가
next-step/atdd-subway-fare pull request #266
Opened 2023-02-27 15:09 UTC by ess234

마지막 주차 1단계 PR 요청드립니다. 
잘 부탁드려요 :)

<img width="738" alt="image" src="https://user-images.githubusercontent.com/25348139/221600822-4267bde1-8c01-47ea-bf31-bd72ff66f287.png">

2023-02-28 09:33 UTC, testrace requested changes
안녕하세요 진윤님 😄 
리뷰를 맡게 된 송용주입니다. 
실습과 1단계 잘 구현해 주셨네요 👍  
다음 단계 진행하기 전에 몇 가지만 수정을 하면 좋을 것 같아요.
관련해서 코멘트 남겨두었는데 확인 후 리뷰 요청 부탁드립니다.
궁금한 점이나 의견 있으시면 편하게 DM 주세요!

2023-02-28 09:33 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathSteps.java
> +    }
경로 조회 요청을 step으로 분리해 주셨네요 👍 
패키지 위치나 클래스명이 인수 테스트에서 사용될 것 같은데 문서화에서만 사용되네요.
인수 테스트와 문서화 모두 사용할 수 있으면 어떨까요?

문서화 실습에서 소개된 Request Parameters, Request and Response Fields 도 적용해 보면 좋을 것 같아요 😄

2023-02-28 09:33 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        line.addSection(역삼역, 삼성역, 5, 20);
필드 하나가 추가되면서 동일한 코드의 변화량이 굉장히 많아졌네요!
그 말은 중복이 많다고 볼 수 있을 것 같은데요.
코드를 변경하기 전에 중복을 먼저 제거하면 코드의 변화량도 줄어들 수 있을 것 같아요.

2023-02-28 09:33 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void findPathByDuration() {
요구사항에 이미 인수 조건이 기재되어 있지만,
인수 테스트를 작성하기 전에 최단 경로, 최소 시간에 대한 인수 조건(시나리오)을 직접 작성해 보시면 어떨까요?

2023-02-28 11:27 UTC, ess234 commented on src/main/java/nextstep/subway/applicaion/dto/PathRequest.java
> +public class PathRequest {
앗 제거하겠습니다.

2023-02-28 11:28 UTC, ess234 commented on src/main/java/nextstep/subway/domain/PathType.java
> +    거리("DISTANCE");
pathtype value 값으로 api pathparam으로도 쓰고 있어서 이렇게 정의했는데 바꿔야 될까요 ???

2023-03-01 06:25 UTC, ess234 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void findPathByDuration() {
이미 있는걸 작성하는건 불필요할 것 같아용 ㅠㅠ 2단계 미션도 언넝 하고싶고용

2023-03-01 06:26 UTC, ess234 commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        line.addSection(역삼역, 삼성역, 5, 20);
말씀하신대로 부모 클래스를 통해 spec 정의하도록 수정했습니당 
인수테스트랑 문서화에서 동일한 step 클래스를 호출할 수 있게 되었습니당

2023-03-01 06:27 UTC, ess234 commented on src/test/java/nextstep/subway/acceptance/PathSteps.java
> +    }
넵 좀더 문서내용을 보강하여 필드별 의미가 표현되도록 수정했습니당

2023-03-01 06:41 UTC, testrace commented on src/main/java/nextstep/subway/domain/PathType.java
> +    거리("DISTANCE");
enum의 경우 기본으로 제공되는 name() 메서드를 활용하면 상수명을 가져올 수 있습니다.
`PathType.DURATION.name()`

[구글 자바 스타일 가이드](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names)에서도 상수는 UPPER_SNAKE_CASE를 사용하도록 하는데요.
일반적으로 UPPER_SNAKE_CASE 로 선언된 이름을 보면 상수라고 판단할 수 있는 반면
한글명은 그 특징을 한번에 파악하기가 쉽지 않아서 영문으로 작성하는게 협업 등에 도움이 될 것 같아요!

2023-03-01 06:53 UTC, testrace approved these changes
안녕하세요 진윤님!
피드백 반영 잘해주셨네요 👍 
소소하게 코멘트 남겼는데 다음 단계 진행하시면서 같이 확인 부탁드릴게요!
궁금한 점이나 의견있으시면 편하게 DM 주세요!

2023-03-01 06:53 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathSteps.java
> +                        )))
요청값과 응답값을 문서에 포함해 주셨네요 👍 
실제 문서에서도 추가된 정보를 확인할 수 있게 index.adoc 파일도 커밋 부탁드립니다!

2023-03-01 06:53 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +        ExtractableResponse<Response> response = searchPath(spec, 교대역, 양재역, PathType.거리.getType());
인수 테스트와 문서화에서 동일한 steps를 활용할 수 있게 되었네요 👍 
메서드명을 기존처럼 한글로 작성하면 인수 테스트 가독성에 도움이 될 것 같아요!

2023-03-01 06:54 UTC, merged