3단계 - 요금 정책 추가
next-step/atdd-subway-fare pull request #273
Opened 2023-02-28 17:23 UTC by codeleesh

안녕하세요, 홍준님

`3단계 - 요금 정책 추가` 요청드립니다.

2단계에서 비슷한 구조를 잡고 진행을 해왔어서 3단계 또한 어렵지 않게 진행할 수 있었습니다.

테스트가 많아지다보니, 한곳의 수정으로 인하여 테스트가 전파가 되면서 수정하는 부분에서 어려움이 있었습니다.

물론, 테스트가 안전망 역할을 하여서 기능 구현 및 리팩토링 또한 어렵지 않게 할 수 있었습니다.

그럼, 소중한 리뷰 기다리고 있겠습니다.

감사합니다.

2023-03-01 12:07 UTC, hjhello423 requested changes
안녕하세요 😀
step3도 잘 진행해 주셨네요. 인수 테스트도 잘 작성해 주셨고요. 👍
한 가지 요구 사항과 맞지 않는 부분이 있어 코멘트를 남겨두었는데요.
금방 수정 가능하실 것 같습니다. 화이팅 🔥

2023-03-01 12:07 UTC, hjhello423 commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +    void findPathByDistance(final int age, final String fare) {
다양한 케이스로 테스트해 주셨네요. 👍

2023-03-01 12:07 UTC, hjhello423 commented on src/test/java/nextstep/subway/unit/PathServiceTest.java
> +    void find_route_by_logout() {
비로그인 까지 👍

2023-03-01 13:26 UTC, codeleesh commented
안녕하세요, 홍준님

리뷰 주신 내용 반영하였습니다!

확인 부탁드립니다!

2023-03-02 06:34 UTC, hjhello423 approved these changes
안녕하세요 😀
시나리오 잘 추가해 주셨군요.
마지막 미션 진행하는 동안 고생하셨습니다.
그럼 이만 머지하도록 하겠습니다! 🔥

2023-03-02 06:35 UTC, merged