step3 - 요금 정책 추가
next-step/atdd-subway-fare pull request #299
Opened 2023-03-03 13:11 UTC by square1324

안녕하세요.
노선 추가 요금 및 연령대별 할인 정책에 대해 테스트와 로직을 작성하였습니다.
마지막으로 리뷰 잘 부탁드립니다.

2023-03-04 12:11 UTC, Flamme1004K requested changes
안녕하세요! 🙇🏻

3단계 미션 잘 구현해 주셨습니다! 💯

몇 가지 코멘트를 남겼으니, 확인 부탁드리겠습니다!

2023-03-04 12:11 UTC, Flamme1004K commented on src/main/java/nextstep/member/domain/AuthenticationPrincipal.java
> +    boolean optional() default false;
대부분 인증 인가에 대한 부분은 optional보다 required를 사용합니다 😊

2023-03-04 12:11 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/Age.java
> +    }
함수화 👍👍

혹시 켄트백 구현 패턴을 읽어보셨나요? 이렇게 함수를 메시지로 감싸는 부분을 켄트백 구현 패턴에서는 설명 메시지라고 합니다. 아직 읽지 않으셨다면 꼭 읽어보시길 바랍니다!

[링크]
- [켄트 벡의 구현 패턴 - 행위](https://itmore.tistory.com/entry/%EC%BC%84%ED%8A%B8-%EB%B2%A1%EC%9D%98-%EA%B5%AC%ED%98%84-%ED%8C%A8%ED%84%B4-%ED%96%89%EC%9C%84)

2023-03-04 12:11 UTC, Flamme1004K commented on src/main/java/nextstep/subway/domain/Fare.java
> +        return fare.operator.apply(distance);
피드백 반영 👍

2023-03-04 12:11 UTC, Flamme1004K commented on src/main/java/nextstep/subway/ui/PathController.java
> +        @RequestParam PathType type) {
request dto로 감싸도 괜찮을 것 같네요~

2023-03-04 12:11 UTC, Flamme1004K commented on src/test/java/nextstep/subway/acceptance/PathExtraFareAcceptanceTest.java
> +     * Given 노선에 추가 요금이 주어지고,
어린이, 청소년, 성인에 대한 인수테스트 👍

2023-03-04 12:11 UTC, Flamme1004K commented on src/test/java/nextstep/subway/domain/AgeTest.java
> +    }
해당 부분은 하나의 `@CsvSource`가 아닌 나누어서 테스트하는게 좋지 않을까하네요. 어떻게 생각하시나요?

2023-03-04 16:14 UTC, square1324 commented on src/test/java/nextstep/subway/domain/AgeTest.java
> +    }
별도의 테스트로 분리하였습니다~

2023-03-05 12:53 UTC, Flamme1004K approved these changes
안녕하세요!

피드백 반영 감사합니다. 이만 머지 하도록 하겠습니다.

그동안 미션 고생하셨습니다. 🙇🏻

2023-03-05 12:53 UTC, Flamme1004K commented on src/main/java/nextstep/subway/ui/PathController.java
> +        @AuthenticationPrincipal(required = false) LoginMember loginMember,
피드백 반영 👍

2023-03-05 12:53 UTC, Flamme1004K commented on src/main/java/nextstep/subway/ui/PathController.java
> +        PathRequest pathRequest) {
dto 사용 👍👍

2023-03-05 12:53 UTC, Flamme1004K commented on src/test/java/nextstep/subway/domain/AgeTest.java
> +        assertThat(Age.ADULT.discountFare(1350)).isEqualTo(1350);
테스트 분리 좋습니다 !🤩

2023-03-05 12:53 UTC, merged