🚀 1단계 - 경로 조회 타입 추가
next-step/atdd-subway-fare pull request #304
Opened 2023-03-04 18:23 UTC by joel-you

안녕하세요 리뷰어님!

문서화 하는게, 생각보다 귀찮은 작업이네요..
리뷰 잘 부탁드리겠습니다!

주말이 다 끝나가지만 좋은 주말 보내세요! 😊

2023-03-05 05:15 UTC, testrace requested changes
안녕하세요 재영님 😃 
1단계 미션 깔끔하게 구현해 주셨네요 👍 
몇 가지 코멘트 남겼는데 확인해 주시고 다시 리뷰 요청 부탁드려요!
궁금한 점이나 의견 있으시면 편하게 DM 주세요.

2023-03-05 05:15 UTC, testrace commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +    }
최소 시간 경로 문서화 테스트를 별도로 만들어 주셨네요 👍 
실제로 문서를 만들어서 확인해 보면 최소 시간 API는 포함이 안되어 있어요 😢  
실제 문서에도 추가를 하면 어떨까요?

2023-03-05 05:15 UTC, testrace commented on src/test/java/nextstep/subway/unit/LineTest.java
> +        line.addSection(역삼역, 삼성역, 5, 3);
필드가 하나 추가되면서 코드 변화량이 굉장히 많아졌네요.
동일한 코드 변화가 반복되면 코드의 중복이라고 볼 수 있을 것 같은데요
변경하기 전에 중복을 제거하고 변경하면 어떨까요?

2023-03-05 05:15 UTC, testrace commented on src/test/java/nextstep/subway/acceptance/PathAcceptanceTest.java
> +     * <p>
setup 메서드에 given이 미리 정의 되어서 인수 테스트를 이해하기 좋아졌네요 👍

2023-03-05 14:37 UTC, joel-you commented
리뷰 주신 부분 수정했습니다.

다만 [이 리뷰](https://github.com/next-step/atdd-subway-fare/pull/304#discussion_r1125599108) 에 대해선 잘 이해가 안되서요.
말씀하신건, 수정전에 기존 테스트코드에는 영향이 가지않도록 메소드를 하나 추가해놓고 진행을 했으면 어떻냐 라는 말씀이신가요 :question:

2023-03-06 01:16 UTC, testrace approved these changes
안녕하세요 재영님!
피드백 반영 잘해주셔서 피드백 드릴 부분이 없네요 👍 
바로 다음 단계로 넘어가시죠!

2023-03-06 01:16 UTC, testrace commented on src/docs/asciidoc/index.adoc
> +operation::pathTime[snippets='http-request,request-parameters,http-response']
요청 필드, 응답 필드에 대한 정보도 있다면 조금 더 상세한 문서를 만들 수 있을 것 같아요 😃

2023-03-06 01:16 UTC, testrace commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +    private void createDocumentationRequest(String identifier, Long sourceId, Long targetId, ShortestPathType type) {
경로 조회 타입이 추가되더라도 쉽게 문서화할 수 있겠네요 👍

2023-03-06 01:16 UTC, merged