🚀 1단계 - 경로 조회 타입 추가
next-step/atdd-subway-fare pull request #319
Opened 2023-03-08 16:18 UTC by cafitac

안녕하세요, 이슬님. 1단계 미션 진행완료하여 리뷰 요청드립니다.

[개발 사항]
- [x] 경로 조회 시 최소 시간 기준으로 조회할 수 있도록 기능을 추가하세요.
- [x] 노선추가 & 구간 추가 시 거리와 함께 소요시간 정보도 추가하세요.
  - [x] 노선 등록 시, 소요 시간 정보를 보내도록 수정
  - [x] 구간 등록 시, 소요 시간 정보를 보내도록 수정
    - [x] 역과 역 사이에 구간을 등록할 시, 기존 구간의 소요 시간도 함께 변경해야함.
      ex) 강남역 - 선릉역 (소요시간 8분), 새로운 구간 강남역 - 역삼역 (소요시간 3분) -> 강남역 - 역삼역 (소요시간 3분), 역삼역 - 선릉역 (소요시간 5분
      

이제 교육 기간이 마무리되어 리뷰어 분들께서 의무적으로 미션에 대한 리뷰를 안해주셔도 되는 것으로 알고 있는데, 해당 주차 미션까지 완주하고 싶어 추가 리뷰 요청은 boorwonie(류성현) 님께 여쭤보면 되는 것인지 질문드립니다!

2023-03-08 16:23 UTC, cafitac commented on src/main/java/nextstep/subway/domain/SubwayDistanceMap.java
> +    }
처음이에는 변경해야하는 곳이` graph.setEdgeWeight(sectionEdge, it.getDistance())` 여기 밖에 없고
단순히 가중치를 distance 가 아닌 duration 으로만 설정하면되기에 새로운 객체를 생성하지 않고 graph 에 한 edge 에 대한 여러 개의 가중치를 설정하는 것이 가능한지 찾아보았습니다.

라이브러리 상에 `WeightedMultigraph<V,​E>` 해당 구현체가 있긴 했으나, 제가 잘못 이해한건지는 잘 몰라도, 한 edge 에 대해 여러 개의 가중치를 설정하는 것이 아니라 여러 값을 받아 하나의 가중치로 설정할 때 사용하는 것 같더라고요.
다시 생각해보았을 때 하나의 edge 에 여러 개의 가중치를 설정하는 것이 불가능한 것처럼 생각되기도 했고요.

그래서 최대한 생각할 수 있는 범위 내에서 SubwayMap 에서 공통 부분을 추출하고 변경 부분만 abstract method 로 분리함으로써 템플리 메서드 패턴을 사용해보고 싶었습니다.

해당 코드에서 더 개선할 수 있는 부분이나 제가 몰랐던 Jgrapht 라이브러리 기능이 있다면 자세하게 리뷰받고 싶어요!

2023-03-10 17:40 UTC, parkeeseul requested changes
리뷰가 많이 늦었네요 🙏 
커밋을 작은 단위로 잘 나누어 주셔서 흐름을 파악하기 좋았습니다 👍 

몇 가지 코멘트 남겨두었으니 확인 부탁드립니다.
즐거운 주말 되세요 🔥

2023-03-10 17:40 UTC, parkeeseul commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> -                    graph.setEdgeWeight(sectionEdge, it.getDistance());
SubwayMap 을 상속하여 구현해 주셨는데요
graph.setEdgeWeight(sectionEdge, it.getDistance()); 시에 
FindType에 따라  distance, duration  를 weight 로 사용하게 하면 
기존 SubwayMap 코드에서 큰 수정 없이 조금 더 간단해 질 수 있을 것 같아요 😄

2023-03-11 07:59 UTC, cafitac commented on src/main/java/nextstep/subway/domain/SubwayDistanceMap.java
> +    }
넵넵 감사합니다!

2023-03-11 08:00 UTC, cafitac commented on src/main/java/nextstep/subway/domain/Sections.java
> +    }
앗 넵넵 감사합니다!!

2023-03-11 08:24 UTC, cafitac commented on src/test/java/nextstep/subway/documentation/LineDocumentation.java
> +            assertThat(response.jsonPath().getString("stations[1].name")).isEqualTo("역삼역");
기존에 작성되어있던 PathDocumentation 에서 response 의 값들을 검증하는 것 때문에 이렇게 작성했었던 것 같습니다!
데이터를 검증하는 것의 의미를 바로 생각했을 때는 LineResponse 를 mocking 하여 넘겼어도 LineResponse DTO 상에서 JsonProperty 를 재정의하여 response 상의 필드 이름이 변경되었을 수 있으니 필드명까지 검사해주는 의미가 있을 것이라고 생각했었습니다.

하지만 RestDocumentationFilter 를 통해 responseFields 에서 필드명을 이미 검사하고 있어서 assertThat() 을 이용한 데이터 검증은 불필요한 절차라고 생각이 되네요!

PathDocumentation 과 LineDocumentation 의 작성 방식의 차이를 보았을 때
- PathDocumentation: responseFields() 를 통해 응답에 대한 adoc 을 생성하지 않기 때문에 assertThat() 을 통해 응답 값을 검증한다.
- LineDocumentation: responseFields() 를 통해 응답에 대한 adoc 을 생성하는 동시에 정의된 필드의 응답 값이 정상적으로 반환되는지 검증한다.
로 생각되는데 두 방식 중 LineDocumentation 방식이 responseFields 에 대한 문서화도 진행하며 검증도 함께 하기 때문에 코드의 양도 줄일 수 있을 것 같고 얻을 수 있는 이점이 더 많다고 생각되었습니다. 🙂

정리해서 이슬님께서 말씀해주신대로 mocking 된 데이터를 검증하는 것은 불필요한 행동으로 판단되나 response 의 필드 이름을 한 번더 검증하는 것은 의미가 있다고 생각되고,
필드 이름을 검증하는 동시에 문서화도 진행할 수 있는 방법인 RestDocumetationFilter 에 responseFields() 를 추가하는 방식을 사용하는 것이 좋을 것 같다고 생각됩니다!!

이미 있는 코드여서 깊게 생각하지 않고 작성했던 것 같은데 왜 이 코드를 작성해야하는지, 어떤 코드가 좋을 것인지 고민할 수 있었던 것 같습니다! 감사합니다!! 🙇‍♂️

2023-03-11 08:56 UTC, cafitac commented
피드백주신 내용 반영하여 수정 후, 재리뷰 요청드립니다!

2023-03-12 12:17 UTC, parkeeseul commented on src/test/java/nextstep/subway/documentation/LineDocumentation.java
> +            assertThat(response.jsonPath().getString("stations[1].name")).isEqualTo("역삼역");
의견 공유 감사합니다 민우님 😄 

말씀 주신 것 처럼 mocking을 했지만 service -> controller 로 전달되는 과정에서 문제가 있을 수도 있으니 
그런 것이라면 검증의 의미가 있다고 생각합니다.
다만 이런 검증 코드들도 비용이니 한번 고민은 해보면 좋을 것 같네요 😄

2023-03-12 12:18 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
즐거운 한주 되시고 다음 미션 진행해 주세요!

2023-03-12 12:18 UTC, merged

2023-03-12 14:53 UTC, cafitac commented on src/test/java/nextstep/subway/documentation/LineDocumentation.java
> +            assertThat(response.jsonPath().getString("stations[1].name")).isEqualTo("역삼역");
넵넵 참고하여 검증 코드들을 작성하기 전에 정말 필요한 코드인지 고민하는 습관을 가져보겠습니다!
감사합니다!