3단계 - 요금 정책 추가
next-step/atdd-subway-fare pull request #379
Opened 2023-08-08 15:05 UTC by kakao-jamesjin

### 작업 내용
- 노선별 추가 요금 기능 추가
- 로그인 사용자의 경우 연령별 요금으로 계산
- 관련 테스트 코드 작성
- 2단계 피드백 반영
-- 문서화 코드 분리

### 테스트
작성한 코드를 포함하여 전체 테스트 동작 확인

### 관련 링크
https://edu.nextstep.camp/s/c30VOHNP/ls/OjFmE3gN

2023-08-09 14:49 UTC, hjhello423 requested changes
안녕하세요 😀
마지막 3단계도 잘 구현해 주셨네요.
몇 가지 코멘트를 달아두었는데 확인 후 다시 한번 리뷰 요청 주세요!

2023-08-09 14:49 UTC, hjhello423 commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    private int extraCharge = 0;
같은 int 타입인데 extraCharge에서만 0으로 초기화하신 이유가 궁금해요!

2023-08-10 01:03 UTC, kakao-jamesjin commented on src/main/java/nextstep/subway/applicaion/dto/LineRequest.java
> +    private int extraCharge = 0;
기존에 사용하던 API라 호환성 때문에 default 값을 넣었어요~
다른 방법도 있는데 코드 변경이 가장 작은 방법으로 진행했습니다.

2023-08-10 01:12 UTC, kakao-jamesjin commented on src/main/java/nextstep/subway/domain/DiscountFarePolicy.java
> +    private int age;
Fare에서 FarePolicy 리스트를 관리하고 있고, FarePolicy interface를 사용하여 계산하고 있어요.

FarePolicy interface는 fare(요금) 외 다른 인자를 넣기는 어려울 것 같은데, 혹시 다른 방법이 있을까요?

2023-08-10 12:11 UTC, kakao-jamesjin commented on src/test/java/nextstep/subway/documentation/PathDocumentation.java
> +        when(pathService.findPath(any(UserPrincipal.class), anyLong(), anyLong(), any(PathType.class))).thenReturn(pathResponse);
token에 고정 값을 넣어서 실패했네요 😭 처리했습니다~

2023-08-10 12:12 UTC, kakao-jamesjin commented
최홍준님 안녕하세요~
말씀하신 피드백 반영 및 코멘트 남겼는데 확인 부탁드려요.
고맙습니다.

2023-08-11 09:49 UTC, hjhello423 approved these changes
안녕하세요. 😀
테스트 코드도 잘 수정해 주셨네요. 👍
미션 진행하는 동안 고생 많으셨습니다!
이만 머지하도록 할게요! 🚀

2023-08-11 09:56 UTC, hjhello423 commented on src/main/java/nextstep/subway/domain/DiscountFarePolicy.java
> +    private int age;
제가 인터페이스로 분리한 부분을 놓쳤군요 🤔

2023-08-11 09:58 UTC, merged