Step3 - 요금 정책 추가
next-step/atdd-subway-fare pull request #62
Opened 2021-03-31 16:49 UTC by bbbnam

안녕하세요 리뷰어님-!
말씀해주신대로 정책이 변경되니까 
기존에 제가 만들었던 FareCalculator 객체는 확장성이 부족한 것 같아서
조금 찾다보니 `전략패턴`이나 `상태패턴`을 이용할 수 있을 거 같아서
전략패턴을 한번 적용해보았습니다.

그로 인해서 변경된 부분이 많아서 코드 짜면서도 많이 헤맨 것 같습니다.😭
오늘도 지적 팍팍 부탁드립니다.

================

[질문이 있습니다] 로그인여부를 필수가 아니라 선택을 해야 할 거 같은데 어떤식으로 접근해야 할지 모르겠습니다.
스프링 시큐리티 찾아보니, 
>  Authentication authentication = SecurityContextHolder.getContext().getAuthentication();

이부분과 SpEL? 이라는 걸 이용할 수 있는 거 같은데,
감이 잘 안와서 로그인이 무조건 되어 있다고 가정하고 미션을 진행했습니다.
이 부분 조언 부탁드립니다

2021-04-01 03:19 UTC, heesunjeong requested changes
자룡님 3단계 미션 구현 잘해주셨어요 👍  
엄청난 커밋양에 깜짝 놀랐어요! TDD사이클을 지키면서 구현해나가신 점 확인할 수 있었습니다 😆 👍 
질문주신 부분과 관련한 부분에 코멘트를 남겼어요! 확인해보시고 반영해보시면 좋을 것 같아요. 
진행하시면서 궁금하신 점은 언제든지 코멘트나 dm을 남겨주세요 :)

2021-04-01 15:56 UTC, bbbnam commented
안녕하세요 리뷰어님-!

리뷰해주신 내용 위주로 리팩토링을 진행해 보았습니다.

- 기존 Fare 객체에서 하던 계산을 -> 정책에서 수행하도록 변경
(이렇게 진행하니 확실히 단위테스트가 더 쉬워지고 각 객체별로 책임을 부여한 거 같아서
좀 더 매끄러워진 거 같습니다.)
- 로그인 여부 필수 or 선택
(강의 시간에 Null object 패턴에 대해서 말씀하신걸 듣고 최대한 구현해보려 했구요, 
더불어서 auth 패키지 내에서 member 패키지를 의존하지 않도록 의존성 제거에 신경을 써 보았습니다. 추가적으로 AuthenticationPrincipal 어노테이션에 required 옵션을 구현해보았습니다.)

오늘도 많은 지적 부탁드립니다.
감사합니다😁

2021-04-02 00:35 UTC, heesunjeong approved these changes
자룡님, 피드백 반영과 로그인하지 않은 사용자에 대한 요청 처리도 아주 잘 해주셨습니다 👍 

미션에 열심히 임해주셨었는데 이번 과정을 통해서 인수 테스트와 단위 테스트가 주는 장점에 대해서 충분히 느껴보셨을 것 같아요 ! 
안정감을 한번 느끼게되면 자연스럽게 테스트를 작성하고 있는 나를 발견하게 되더라구요!ㅎㅎ 자룡님도 이번 과정이 그런 계기가 되셨길 바랍니다 :)

마지막까지 미션까지 너무 고생 많으셨습니다 👏 🎉  머지하도록 하겠습니다~!

2021-04-02 00:35 UTC, merged

2021-04-02 00:36 UTC, bbbnam commented on src/main/java/nextstep/subway/member/domain/Anonymous.java
> +        if (Objects.isNull(notLogin)) {
그..그렇군요 ㅋ 불필요한 싱글턴이었네요