도전 - 가장 빠른 도착 경로 조회
next-step/atdd-subway-fare pull request #78
Opened 2021-04-07 14:03 UTC by jsyang-dev

안녕하세요.
도전 미션을 진행해 보았습니다.
시간이 부족해서 마무리를 대충 한 느낌이 있네요..ㅠ

## 요구사항

- 가장 빨리 도착할 수 있는 경로를 조회하는 기능을 구현

2021-04-09 12:35 UTC, junwoochoi requested changes
안녕하세요 정수님!! 

도전과제에 도전해주셔서 감사합니다 👍 👍 
제가 개인적인 업무로 인해서 리뷰가 하루정도 늦어졌네요 ㅠㅠ 죄송합니다.

테스트케이스도 잘만들어주시고, 문서화 및 기능 구현도 잘해주셨습니다!! 😄 
혹시 도움이 될까 몇가지 코멘트 드렸는데 확인 확인해보시면 좋을 것 같습니다!! 혹시 다른 의견이나 질문 있으시면 편하게 의견주세요! :D

2021-04-09 12:35 UTC, junwoochoi commented on src/main/java/nextstep/subway/path/domain/SubwayTime.java
> +    public LocalDateTime getNextStartTime(Station source, LocalDateTime dateTime) {
Test를 위해 public 접근자로 만드신걸까요? 👀

2021-04-09 12:35 UTC, junwoochoi commented on src/main/java/nextstep/subway/path/domain/SubwayTime.java
> +        int addTime = line.getSections().getAddTimeBetweenSourceAndTarget(source, target);
디미터 법칙을 활용해서 
line객체에게 해당 내용에 대해 묻도록 해보면 어떨까요?

2021-04-09 12:35 UTC, junwoochoi commented on src/main/java/nextstep/subway/path/domain/SubwayTime.java
> +        int addTime = line.getSections().getAddTimeFromUpStation(source);
아래와 같은 맥락으로 line.getAddTimeFromUpStation(source) 이런 식으로 처리하고, 라인객체 내에서 sections를 활용하도록 해보면 좋을 것 같아요 :)

2021-04-09 12:35 UTC, junwoochoi commented on src/test/java/nextstep/subway/path/domain/SubwayTimeTest.java
> +    }
예외 케이스를 찾아서 잘 테스트해주셨네요 👍 👍

2021-04-09 12:35 UTC, junwoochoi commented on src/test/java/nextstep/subway/path/domain/SubwayPathTimeTest.java
> +        assertThat(arriveTime).isEqualTo(LocalDateTime.of(2021, 4, 5, 5, 21));
요 케이스 실패하는 것 같은데 확인 가능하실까요??

```
4호선 강남 -- 5분 -- 삼성       5시08분 탑승 | 5시13분 하차
3호선 삼성 -- 3분 -- 사당       5시17분 탑승 | 5시20분 하차
```

해서 20분 도착이라고 생각했는데 혹시 저랑 다르게 계산하셨을까요?

![image](https://user-images.githubusercontent.com/26688947/114180120-c4b22080-997a-11eb-8dcf-a19db6156388.png)

2021-04-09 12:35 UTC, junwoochoi commented on src/test/java/nextstep/subway/path/domain/SubwayPathTimeTest.java
> +    @DisplayName("도착 시간 구하기")
`getFastPathResult` 에 대한 테스트도 추가해보면 좋을 것 같습니다!

2021-04-12 13:20 UTC, jsyang-dev commented on src/main/java/nextstep/subway/path/domain/SubwayPathTime.java
> +    }
이부분이 뭔가 찝찝했는데 이거였네요ㅎㅎ
일단은 FastPathResult 객체를 domain 패키지에 생성했는데, 이런 객체는 domain과 dto 중에 어떤걸로 봐야 할까요?

2021-04-12 13:25 UTC, jsyang-dev commented on src/main/java/nextstep/subway/path/domain/SubwayTime.java
> +    public LocalDateTime getNextStartTime(Station source, LocalDateTime dateTime) {
getNextStartTime 메서드에 대한 TDD 개발 후, getArriveTime 메서드에 대한 TDD를 진행하다 보니 테스트에서 사용하기 위해 public 상태가 되어버렸네요.
private 접근자로 변경하였습니다.

2021-04-12 13:33 UTC, jsyang-dev commented on src/main/java/nextstep/subway/path/domain/SubwayTime.java
> +        int addTime = line.getSections().getAddTimeFromUpStation(source);
디미터의 법칙을 잠시 망각했었던 것 같습니다ㅎ

2021-04-12 13:35 UTC, jsyang-dev commented on src/test/java/nextstep/subway/path/domain/SubwayPathTimeTest.java
> +        assertThat(arriveTime).isEqualTo(LocalDateTime.of(2021, 4, 5, 5, 21));
20분이 맞는 것 같습니다!!

2021-04-12 13:46 UTC, jsyang-dev commented
바쁘신 와중에도 꼼꼼하게 피드백 주셔서 감사합니다!!
주말에 일이 있어서 이제야 확인 했네요ㅠ
피드백 수정해서 다시 PR 요청 드립니다~

2021-04-12 23:55 UTC, junwoochoi commented on src/main/java/nextstep/subway/line/domain/Sections.java
> +        List<Section> sortedSections = new ArrayList<>(Collections.singletonList(section));
이건 제 개인적인 기준이긴 하지만, `Collections.singletonList`함수는 타고 들어가보면 immutable 한 리스트를 반환하는데, 그거를 뭔가 다른 mutable한 객체에 넣은 다음에, 거기에 add를 하니까 어색하게 느껴져서 질문을 드렸던 것 같아요 :)

지금 이대로도 문제 없을 것 같습니다!

2021-04-13 10:14 UTC, junwoochoi approved these changes
안녕하세요! 정수님! 
강의가 끝나서 의욕이 사라지기 쉬운 상황에도 끝까지 열심히 진행해주셔서 감사합니다!!
저도 본받아야될 것 같습니다 😄 

마지막까지 고생많으셨고, 앞으로도 ATDD 관련한 학습 및 전파에 꾸준히 관심가지시기를 응원하겠습니다!!!
감사합니다!! 🙇

2021-04-13 10:14 UTC, junwoochoi commented on src/main/java/nextstep/subway/path/application/PathService.java
> +            FastPathResult fastPathResult = subwayPathTime.getFastPathResult(datetime);
👍

2021-04-13 10:14 UTC, junwoochoi commented on src/main/java/nextstep/subway/path/domain/SubwayTime.java
> +        int addTime = line.getAddTimeBetweenSourceAndTarget(source, target);
피드백 적용 👍 👍

2021-04-13 10:14 UTC, merged

2021-04-13 12:33 UTC, jsyang-dev commented
저도 이번 교육을 통해서 많은 것을 배웠던 것 같습니다.
특히 준우님의 리뷰가 도움이 많이 됐습니다~ 감사합니다!!🙇