Step3
next-step/atdd-subway-fare pull request #80
Opened 2021-04-11 15:13 UTC by boraming9

(늦어서 죄송합니다^^;)
step2 피드백 반영
step3 요금 정책 추가 기능, 단위테스트

2021-04-12 12:53 UTC, ivvve requested changes
안녕하세요 보람님~
기간이 지난 후에도 미션을 잘 진행해주고 계시는군요 👍 

구현을 하면서 어느정도 구현에 대한 고민도 많이 하신 것 같고 테스트 코드도 잘 짜셨네요!

지금도 코드가 좋긴하나 구현 관련해서 몇 가지 코멘트 남겼으니 확인 부탁드리겠습니다 :)

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/path/enums/AgeFarePolicy.java
> +                ageFarePolicy.getAgeFrom() <= age && ageFarePolicy.getAgeTo() >= age
지금 코드도 좋지만
이 비교문도 메서드화 했다면 가독성에 더 도움이 되었을 것 같습니다 :)

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/path/enums/DistanceFarePolicy.java
> +    final private int maximumFare;
이 값은 비지니스 규칙에 포함되지 않은 부분인데요
(규칙은 aKM ~ bKM 이런식으로 표현되죠)
로직 구현을 위해 이렇게 개발 쪽에서만 통용되는 값을 넣는 것이 좋을지 고려해보시면 좋을 것 같습니다 :)

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/path/application/FareCalculator.java
> +    private final int BASIC_FARE = 1250;
기본 요금은 우리 도메인에 있어서 매우 중요한 값인데요!
이러한 값이 application layer에 있는 것이 좋을지 생각해보시면 좋을 것 같습니다 :)

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/auth/domain/AuthenticationPrincipal.java
> +    boolean required() default true;
Spring의 annotation들 처럼 `required`를 도입하셨군요 :+1:

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/path/enums/AgeFarePolicy.java
> +public enum AgeFarePolicy {
Policy enum도 비지니스 로직을 표현하기 위함이니 domain layer에 두는 편이 좋지 않을까 싶습니다 :thinking:

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/path/domain/policy/FarePolicyCalculator.java
> +    }
지금과 같이 `support`라는 메서드를 통해 총합을 더 해가는 방식에 대해 더 고려해보시면 좋을 것 같은데요!

1. support(s) 라는 네이밍은 Filter와 같은 클래스에서 입력으로 들어온 파라미터를 지원하는지 여부를 확인하기위해 주로 사용됩니다.
2. 재귀로 로직을 구현하셨는데 현재 로직에서 List로 객체들을 갖는 방식이 아닌 지금과 같은 chain 구조가 과연 좋을지에 대해서도 생각해보시면 좋을 것 같습니다.

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/path/domain/policy/AgeFarePolicyCalculator.java
> +public class AgeFarePolicyCalculator extends FarePolicyCalculator {
비지니스 규칙에 대한 값들을 담고 있는 Policy가 있는데
Calculator를 사용하여 오히려 복잡도를 높히는 것은 아닐지도 고민해보시면 좋을 것 같습니다 :)

2021-04-12 12:53 UTC, ivvve commented on src/main/java/nextstep/subway/member/domain/EmptyMember.java
> +        super(null, EMPTY_INFO, EMPTY_INFO, 30);
age 값을 하드코딩하는 것보단 나이에 대한 상수를 사용하면 보다 의미 있을 것 같습니다!

2021-04-12 12:53 UTC, ivvve commented on src/test/java/nextstep/subway/path/application/FareCalculatorTest.java
> +public class FareCalculatorTest {
복잡한 로직에 대해서 단위 테스트 :100:

2021-04-14 12:09 UTC, boraming9 commented on src/main/java/nextstep/subway/path/domain/policy/FarePolicyCalculator.java
> +    }
chain구조가 아닌 Fare 도메인을 생성하여 FareCalculator에서 순차적으로 각 Policy별 fare를 순차 계산하는 방식으로 변경했는데 이 구조는 어떤지요?

2021-04-14 12:10 UTC, boraming9 commented on src/main/java/nextstep/subway/path/domain/policy/AgeFarePolicyCalculator.java
> +public class AgeFarePolicyCalculator extends FarePolicyCalculator {
위와 같이 Chain구조를 풀면서 FareCalculator들로 해당 로직을 옮겼습니다.

2021-04-14 12:11 UTC, boraming9 commented on src/main/java/nextstep/subway/path/application/FareCalculator.java
> +    private final int BASIC_FARE = 1250;
Fare 도메인이 가지고 있도록 변경했는데, 적절한 방법이 맞는지 리뷰어님이 생각하신 적당한 위치는 어디였을까요?!

2021-04-18 14:41 UTC, boraming9 commented
Step3: 피드백 반영, 인수/단위테스트 확인

2021-04-20 14:03 UTC, ivvve approved these changes
보람님 마지막 미션도 고생하셨습니다!

이번주에 몸 상태가 너무 안좋아서 리뷰가 조금 늦었네요 죄송합니다ㅠ

이번 미션을 통해서 인수 테스트, 단위 테스트는 물론이고
- 지금 기능 외에도 추가 요구사항이 들어왔을 때도 쉽게 적용이 가능할까?
- 내 코드를 보았을 때 다른 사람도 쉽게 이해할 수 있을까?
에 대해서도 충분한 고민을 할 수 있었다면 좋겠습니다 :)

수고 많으셨구요!
이번 과정을 통해서 테스트에 대해 보다 많은 인사이트를 얻어가셨다면 좋겠습니다 :)
고생 많으셨습니다 🥇 

--

앞서 리뷰 코멘트에 댓글이 안달려서 여기에 답변합니다!

https://github.com/next-step/atdd-subway-fare/pull/80#discussion_r613190445
> Fare 도메인이 가지고 있도록 변경했는데, 적절한 방법이 맞는지 리뷰어님이 생각하신 적당한 위치는 어디였을까요?!

저도 도메인에 두는 것이었습니다만, Fare 보다는 요금을 계산하는 FareCalculator에 두는 편이 좋지않을까라는 생각입니다 :)

2021-04-20 14:03 UTC, merged