Step2 요금 조회 리뷰 요청드립니다.
next-step/atdd-subway-fare pull request #99
Opened 2022-02-15 11:20 UTC by itdar

안녕하세요 이슬님!~
1단계 재리뷰 요청 후에 2단계를 슬슬 하고있었는데.. 1단계 머지해주시자마자 곧바로 2단계를 요청드리는 것 같아서...
천천히 해주십셔..ㅎㅎ
소요시간 기준으로 경로를 뽑아내도 요금은 최단거리 기준으로 책정된다는게 좀 지저분한 듯? 했지만.. 리팩토링을 했습니다.
이번에도 감사합니다! 좋은 저녁되세요!!

2022-02-17 12:06 UTC, parkeeseul requested changes
2단계 미션 잘 진행해주셨녜요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다 😄 
즐거운 저녁 되세요! 🔥

2022-02-17 12:39 UTC, itdar commented on src/main/java/nextstep/subway/domain/Path.java
> +    private int fareDistance;
앗 감사합니다! 쭉 읽어봐야겠네요

2022-02-17 12:41 UTC, itdar commented on src/test/java/nextstep/subway/unit/PathServiceTest.java
> +    @DisplayName("11km 거리의 경로조회 (최소시긴 경로와 다른 경로) 를 한다.")
크 역시.. 👍🏼 👍🏼 👍🏼 👍🏼

2022-02-17 13:16 UTC, itdar commented on src/main/java/nextstep/subway/domain/SubwayMap.java
> +    private int fareDistance;
아 관리 개념으로 보니까 다 필요가 없네요...ㅎㅎ 싹 지웠습니다
생성하게 되는 것은 다음단계에서 진행 중인데 리팩토링 시에 생각해서 처리해보겠습니다!!

2022-02-17 13:16 UTC, itdar commented on src/test/java/nextstep/subway/domain/PathTest.java
> +class PathTest {
앗 그 요구사항을 빠뜨렸네요.. 추가해서 커밋합니다!!

2022-02-18 12:05 UTC, parkeeseul approved these changes
피드백 잘 진행해주셨네요! 👍 
한 가지 소소한 코멘트 남겨두었으니 확인 부탁드리고
다음 단계 진행해주세요! 😄 
즐거운 금요일 밤 되세요 🔥

2022-02-18 12:06 UTC, merged

2022-02-18 12:12 UTC, itdar commented on src/main/java/nextstep/subway/domain/Path.java
> +    protected int getOverFare(int distance) {
옙 쓰면서도 긴가민가 했었는데 수정해보겠습니다!~